# Generated by Django 3.0.5 on 2023-07-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_auto_20230715_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('AB+', 'AB+'), ('B+', 'B+'), ('A', 'A'), ('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('AB-', 'AB-'), ('B-', 'B-')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=8),
        ),
    ]
