# Generated by Django 3.0.5 on 2023-07-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_auto_20230715_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('O-', 'O-'), ('O+', 'O+'), ('B+', 'B+'), ('A+', 'A+'), ('B-', 'B-'), ('AB-', 'AB-'), ('A', 'A'), ('AB+', 'AB+')], max_length=10),
        ),
    ]
