# Generated by Django 3.0.5 on 2023-07-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0008_auto_20230715_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('B+', 'B+'), ('O+', 'O+'), ('AB-', 'AB-'), ('A+', 'A+'), ('A', 'A'), ('AB+', 'AB+'), ('B-', 'B-'), ('O-', 'O-')], max_length=10),
        ),
    ]
