# Generated by Django 3.0.5 on 2023-07-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0011_auto_20230715_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('O-', 'O-'), ('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB-', 'AB-'), ('A', 'A'), ('AB+', 'AB+'), ('B-', 'B-')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Pending', max_length=8),
        ),
    ]
