# Generated by Django 3.0.5 on 2023-07-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0013_auto_20230715_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('AB-', 'AB-'), ('B+', 'B+'), ('O+', 'O+'), ('A+', 'A+'), ('O-', 'O-'), ('B-', 'B-'), ('A', 'A'), ('AB+', 'AB+')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=8),
        ),
    ]
