# Generated by Django 3.0.5 on 2023-07-15 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0014_auto_20230715_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='id',
        ),
        migrations.AddField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(default=uuid.UUID('75640168-9fd1-4f2a-a8e3-7dc512d8f51c'), max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='donor',
            field=models.CharField(default='ASAP', max_length=20),
        ),
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A+'), ('AB+', 'AB+'), ('B+', 'B+'), ('AB-', 'AB-'), ('A', 'A'), ('O+', 'O+'), ('B-', 'B-'), ('O-', 'O-')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=8),
        ),
    ]
