# Generated by Django 3.0.5 on 2023-07-15 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0015_auto_20230715_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('O+', 'O+'), ('B+', 'B+'), ('AB-', 'AB-'), ('A', 'A'), ('O-', 'O-'), ('A+', 'A+'), ('B-', 'B-'), ('AB+', 'AB+')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(default=uuid.UUID('2a9bfa94-f6ba-41b7-965e-3ea50ae48035'), max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=8),
        ),
    ]
