# Generated by Django 3.0.5 on 2023-07-15 22:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0025_auto_20230716_0114'),
        ('donor', '0018_auto_20230715_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Plasma', 'Plasma'), ('Power Red', 'Power Red'), ('Blood', 'Blood'), ('Platelets', 'Platelets')], default='Blood', max_length=10)),
                ('no_of_donations', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='blooddonate',
            name='bloodgroup',
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O-', 'O-'), ('A', 'A'), ('O+', 'O+'), ('AB+', 'AB+'), ('B+', 'B+'), ('B-', 'B-'), ('AB-', 'AB-'), ('A+', 'A+')], max_length=3),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='volunteer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.VolunteerRegistration'),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='donation_id',
            field=models.CharField(default=uuid.UUID('c13bee6a-06c8-4b0b-bf47-51d0b62940ad'), max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('O-', 'O-'), ('A', 'A'), ('O+', 'O+'), ('AB+', 'AB+'), ('B+', 'B+'), ('B-', 'B-'), ('AB-', 'AB-'), ('A+', 'A+')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(default=uuid.UUID('963e0eae-5d38-4516-8a4e-a92458d904f8'), max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=8),
        ),
        migrations.CreateModel(
            name='PreExamInfo',
            fields=[
                ('pre_exam_id', models.CharField(default=uuid.UUID('cd3a533b-fa34-41e1-92a9-09ad70889462'), max_length=10, primary_key=True, serialize=False)),
                ('haemoglobin_gDL', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature_C', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blood_pressure', models.CharField(default='0/0', max_length=10)),
                ('pulse_rate_BPM', models.PositiveIntegerField(default=0)),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.Donor')),
            ],
        ),
        migrations.CreateModel(
            name='DonorHealthInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_on', models.DateTimeField(auto_now_add=True)),
                ('blood_group', models.CharField(blank=True, choices=[('O-', 'O-'), ('A', 'A'), ('O+', 'O+'), ('AB+', 'AB+'), ('B+', 'B+'), ('B-', 'B-'), ('AB-', 'AB-'), ('A+', 'A+')], max_length=3, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('gender', models.CharField(choices=[('M', 'M'), ('Nil', 'Nil'), ('F', 'F')], default='Nil', max_length=3)),
                ('next_safe_date', models.DateField(blank=True)),
                ('donor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donor.Donor')),
            ],
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='donation_type',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='donor.DonationType'),
        ),
    ]
