# Generated by Django 3.0.5 on 2023-07-16 07:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0019_auto_20230716_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('B+', 'B+'), ('AB-', 'AB-'), ('B-', 'B-'), ('A+', 'A+'), ('O-', 'O-'), ('A', 'A'), ('AB+', 'AB+'), ('O+', 'O+')], max_length=3),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='donation_id',
            field=models.CharField(default=uuid.UUID('72c8bc46-0313-4eea-a4f1-50c6efffbc71'), max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donationtype',
            name='type',
            field=models.CharField(choices=[('Plasma', 'Plasma'), ('Platelets', 'Platelets'), ('Blood', 'Blood'), ('Power Red', 'Power Red')], default='Blood', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('B+', 'B+'), ('AB-', 'AB-'), ('B-', 'B-'), ('A+', 'A+'), ('O-', 'O-'), ('A', 'A'), ('AB+', 'AB+'), ('O+', 'O+')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(default=uuid.UUID('748c44e0-80b6-4153-bbd5-f9a4b80a4c37'), max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('B+', 'B+'), ('AB-', 'AB-'), ('B-', 'B-'), ('A+', 'A+'), ('O-', 'O-'), ('A', 'A'), ('AB+', 'AB+'), ('O+', 'O+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='gender',
            field=models.CharField(choices=[('Nil', 'Nil'), ('F', 'F'), ('M', 'M')], default='Nil', max_length=3),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='taken_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='pre_exam_id',
            field=models.CharField(default=uuid.UUID('23041d14-0817-42e6-8a3c-718838836f58'), max_length=10, primary_key=True, serialize=False),
        ),
    ]
