# Generated by Django 4.2.3 on 2023-07-17 06:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0020_auto_20230716_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('A', 'A'), ('O+', 'O+'), ('B+', 'B+'), ('B-', 'B-'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='donation_id',
            field=models.CharField(default=uuid.UUID('75ff4b78-5dfd-45b9-a58d-bfdfc4cd8d65'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donationtype',
            name='type',
            field=models.CharField(choices=[('Plasma', 'Plasma'), ('Blood', 'Blood'), ('Platelets', 'Platelets'), ('Power Red', 'Power Red')], default='Blood', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('A', 'A'), ('O+', 'O+'), ('B+', 'B+'), ('B-', 'B-'), ('O-', 'O-')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(default=uuid.UUID('4a156eca-f4f2-40b5-acf6-78fb602ba39c'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('A', 'A'), ('O+', 'O+'), ('B+', 'B+'), ('B-', 'B-'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='taken_on',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='pre_exam_id',
            field=models.CharField(default=uuid.UUID('8a0e744f-d745-4d75-a942-7a3850fc22a4'), max_length=10, primary_key=True, serialize=False),
        ),
    ]
