# Generated by Django 4.2.3 on 2023-07-17 08:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0021_alter_blooddonate_blood_group_alter_blooddonate_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('B+', 'B+'), ('AB-', 'AB-'), ('B-', 'B-'), ('A', 'A'), ('O+', 'O+'), ('A+', 'A+'), ('AB+', 'AB+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='donation_id',
            field=models.CharField(default=uuid.UUID('44c953fe-002c-482d-9415-1b04ea0affc7'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donationtype',
            name='type',
            field=models.CharField(choices=[('Power Red', 'Power Red'), ('Blood', 'Blood'), ('Plasma', 'Plasma'), ('Platelets', 'Platelets')], default='Blood', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('B+', 'B+'), ('AB-', 'AB-'), ('B-', 'B-'), ('A', 'A'), ('O+', 'O+'), ('A+', 'A+'), ('AB+', 'AB+'), ('O-', 'O-')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(default=uuid.UUID('3a4e3a64-c73e-4bb9-a3a1-755b728c7228'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('B+', 'B+'), ('AB-', 'AB-'), ('B-', 'B-'), ('A', 'A'), ('O+', 'O+'), ('A+', 'A+'), ('AB+', 'AB+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F'), ('Nil', 'Nil')], default='Nil', max_length=3),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='pre_exam_id',
            field=models.CharField(default=uuid.UUID('29f4a508-56f4-47ea-9bb0-ebb36e698f0c'), max_length=10, primary_key=True, serialize=False),
        ),
    ]
