# Generated by Django 4.2.3 on 2023-07-17 17:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0035_alter_hostedblooddrives_county_and_more'),
        ('donor', '0024_alter_blooddonate_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='served_by',
            field=models.ForeignKey(blank=True, default='delete-101', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='appointments.volunteerregistration'),
        ),
        migrations.AddField(
            model_name='preexaminfo',
            name='volunteer_id',
            field=models.ForeignKey(blank=True, default='delete-101', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='appointments.volunteerregistration'),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('B-', 'B-'), ('AB-', 'AB-'), ('A+', 'A+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A', 'A'), ('O-', 'O-'), ('B+', 'B+')], max_length=3),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='donation_id',
            field=models.CharField(default=uuid.UUID('a47b3574-2c50-4f25-a3f9-f968edf295b5'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('B-', 'B-'), ('AB-', 'AB-'), ('A+', 'A+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A', 'A'), ('O-', 'O-'), ('B+', 'B+')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(default=uuid.UUID('c2a95e69-53aa-4d4b-bfcb-69219cdb750b'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('B-', 'B-'), ('AB-', 'AB-'), ('A+', 'A+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A', 'A'), ('O-', 'O-'), ('B+', 'B+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='gender',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M'), ('Nil', 'Nil')], default='Nil', max_length=3),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='donor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donor.donor'),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='pre_exam_id',
            field=models.CharField(default=uuid.UUID('e5f35ce8-8956-478d-b670-b299c19f9e9b'), max_length=10, primary_key=True, serialize=False),
        ),
    ]
