# Generated by Django 4.2.3 on 2023-07-17 20:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0025_donor_served_by_preexaminfo_volunteer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonate',
            name='date',
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='created_date',
            field=models.DateTimeField(default='2023-07-17 23:38:31'),
        ),
        migrations.AddField(
            model_name='donor',
            name='created_date',
            field=models.DateTimeField(default='2023-07-17 23:38:31'),
        ),
        migrations.AddField(
            model_name='preexaminfo',
            name='created_date',
            field=models.DateTimeField(default='2023-07-17 23:38:31'),
        ),
        migrations.AddField(
            model_name='preexaminfo',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B+', 'B+'), ('A+', 'A+'), ('B-', 'B-'), ('O-', 'O-'), ('AB+', 'AB+'), ('O+', 'O+'), ('AB-', 'AB-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='donation_id',
            field=models.CharField(default=uuid.UUID('55b4fca2-0a03-4d57-b790-13588a52274d'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donationtype',
            name='type',
            field=models.CharField(choices=[('Power Red', 'Power Red'), ('Blood', 'Blood'), ('Plasma', 'Plasma'), ('Platelets', 'Platelets')], default='Blood', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('A+', 'A+'), ('B-', 'B-'), ('O-', 'O-'), ('AB+', 'AB+'), ('O+', 'O+'), ('AB-', 'AB-')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(default=uuid.UUID('0c962cc4-12df-40ce-92f9-5b5455b972eb'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B+', 'B+'), ('A+', 'A+'), ('B-', 'B-'), ('O-', 'O-'), ('AB+', 'AB+'), ('O+', 'O+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='gender',
            field=models.CharField(choices=[('F', 'F'), ('Nil', 'Nil'), ('M', 'M')], default='Nil', max_length=3),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='pre_exam_id',
            field=models.CharField(default=uuid.UUID('06622f52-2064-486f-83eb-5bffac125ed2'), max_length=10, primary_key=True, serialize=False),
        ),
    ]
