# Generated by Django 4.2.3 on 2023-07-24 04:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0029_donor_county_alter_blooddonate_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('AB+', 'AB+'), ('B-', 'B-'), ('O-', 'O-'), ('B+', 'B+'), ('O+', 'O+'), ('AB-', 'AB-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 7, 25, 4, 81194)),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='donation_id',
            field=models.CharField(default=uuid.UUID('4f48fba8-91b0-4f26-a5a6-7df297cbfe01'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donationtype',
            name='type',
            field=models.CharField(choices=[('Power Red', 'Power Red'), ('Blood', 'Blood'), ('Platelets', 'Platelets'), ('Plasma', 'Plasma')], default='Blood', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('AB+', 'AB+'), ('B-', 'B-'), ('O-', 'O-'), ('B+', 'B+'), ('O+', 'O+'), ('AB-', 'AB-')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='county',
            field=models.CharField(choices=[('Uasin Gishu', 'Uasin Gishu'), ('Kisumu', 'Kisumu'), ('Samburu', 'Samburu'), ('Bomet', 'Bomet'), ('Taita-Taveta', 'Taita-Taveta'), ('Kakamega', 'Kakamega'), ('Embu', 'Embu'), ('Marsabit', 'Marsabit'), ('Kisii', 'Kisii'), ('Turkana', 'Turkana'), ('Makueni', 'Makueni'), ('Isiolo', 'Homa Bay'), ('Machakos', 'Machakos'), ('Laikipia', 'Laikipia'), ('Migori', 'Migori'), ('Busia', 'Busia'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Siaya', 'Siaya'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Narok', 'Narok'), ('Garissa', 'Garissa'), ('Nandi', 'Nandi'), ('Nakuru', 'Nakuru'), ('Wajir', 'Wajir'), ('Kitui', 'Kitui'), ('Kwale', 'Kwale'), ('Bungoma', 'Bungoma'), ('Vihiga', 'Vihiga'), ('Kiambu', 'Kiambu'), ('Kajiado', 'Kajiado'), ('Baringo', 'Baringo'), ('Nyandarua', 'Nyandarua'), ('Homa Bay', 'Homa Bay'), ('Kirinyaga', 'Kirinyaga'), ('Nyamira', 'Nyamira'), ('Nyeri', 'Nyeri'), ('Trans Nzoia', 'Trans Nzoia'), ('West Pokot', 'West Pokot'), ("Murang'a", "Murang'a"), ('Mandera', 'Mandera'), ('Kilifi', 'Kilifi'), ('Kericho', 'Kericho'), ('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Tana River', 'Tana River'), ('Meru', 'Meru'), ('Lamu', 'Lamu')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='donor',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 7, 25, 4, 78199)),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(default=uuid.UUID('afdba9a6-cef2-4a65-affd-483dda80b3c5'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('AB+', 'AB+'), ('B-', 'B-'), ('O-', 'O-'), ('B+', 'B+'), ('O+', 'O+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('Nil', 'Nil'), ('F', 'F')], default='Nil', max_length=3),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 7, 25, 4, 79198)),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='pre_exam_id',
            field=models.CharField(default=uuid.UUID('48d1175c-7b70-40f7-8c2f-25e101628579'), max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2023, 7, 24, 7, 25, 4, 82197))),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donor')),
            ],
        ),
    ]
