# Generated by Django 4.2.3 on 2023-07-24 06:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donor', '0030_alter_blooddonate_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notifications/attachments/'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notifications',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O-', 'O-'), ('A', 'A'), ('B+', 'B+'), ('A+', 'A+'), ('AB+', 'AB+'), ('B-', 'B-'), ('O+', 'O+'), ('AB-', 'AB-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 9, 12, 23, 553826)),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='donation_id',
            field=models.CharField(default=uuid.UUID('66740eba-950c-437c-86d2-eeaf5e50e049'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donationtype',
            name='type',
            field=models.CharField(choices=[('Plasma', 'Plasma'), ('Blood', 'Blood'), ('Platelets', 'Platelets'), ('Power Red', 'Power Red')], default='Blood', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('O-', 'O-'), ('A', 'A'), ('B+', 'B+'), ('A+', 'A+'), ('AB+', 'AB+'), ('B-', 'B-'), ('O+', 'O+'), ('AB-', 'AB-')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='county',
            field=models.CharField(choices=[('West Pokot', 'West Pokot'), ('Embu', 'Embu'), ('Siaya', 'Siaya'), ('Kirinyaga', 'Kirinyaga'), ('Garissa', 'Garissa'), ('Machakos', 'Machakos'), ('Kwale', 'Kwale'), ('Kisii', 'Kisii'), ('Uasin Gishu', 'Uasin Gishu'), ('Narok', 'Narok'), ('Taita-Taveta', 'Taita-Taveta'), ('Nyeri', 'Nyeri'), ('Tana River', 'Tana River'), ('Meru', 'Meru'), ('Kakamega', 'Kakamega'), ('Vihiga', 'Vihiga'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Laikipia', 'Laikipia'), ('Wajir', 'Wajir'), ('Nyamira', 'Nyamira'), ('Trans Nzoia', 'Trans Nzoia'), ('Kitui', 'Kitui'), ('Makueni', 'Makueni'), ('Kiambu', 'Kiambu'), ('Turkana', 'Turkana'), ('Samburu', 'Samburu'), ('Bungoma', 'Bungoma'), ('Bomet', 'Bomet'), ("Murang'a", "Murang'a"), ('Kericho', 'Kericho'), ('Kilifi', 'Kilifi'), ('Kajiado', 'Kajiado'), ('Nyandarua', 'Nyandarua'), ('Mombasa', 'Mombasa'), ('Lamu', 'Lamu'), ('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Nandi', 'Nandi'), ('Isiolo', 'Homa Bay'), ('Kisumu', 'Kisumu'), ('Homa Bay', 'Homa Bay'), ('Baringo', 'Baringo'), ('Migori', 'Migori'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Marsabit', 'Marsabit'), ('Mandera', 'Mandera'), ('Busia', 'Busia')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='donor',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 9, 12, 23, 540835)),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(default=uuid.UUID('55764b6e-85f0-4bb8-b7be-d6c09e910aaf'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O-', 'O-'), ('A', 'A'), ('B+', 'B+'), ('A+', 'A+'), ('AB+', 'AB+'), ('B-', 'B-'), ('O+', 'O+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='gender',
            field=models.CharField(choices=[('F', 'F'), ('Nil', 'Nil'), ('M', 'M')], default='Nil', max_length=3),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 9, 12, 23, 555826)),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 9, 12, 23, 543833)),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='pre_exam_id',
            field=models.CharField(default=uuid.UUID('bdcf3b32-a4d5-489d-bc03-0da9c5a0a10f'), max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Pending', max_length=8),
        ),
    ]
