# Generated by Django 4.2.3 on 2023-07-24 10:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0031_notifications_attachment_notifications_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('A+', 'A+'), ('AB+', 'AB+'), ('B-', 'B-'), ('O-', 'O-'), ('A', 'A'), ('B+', 'B+'), ('AB-', 'AB-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 13, 52, 36, 530947)),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='donation_id',
            field=models.CharField(default=uuid.UUID('cd7ea374-4721-40c1-9c27-b5baf36049d0'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='donation_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='donor.donationtype'),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donationtype',
            name='type',
            field=models.CharField(choices=[('Power Red', 'Power Red'), ('Blood', 'Blood'), ('Plasma', 'Plasma'), ('Platelets', 'Platelets')], default='Blood', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('O+', 'O+'), ('A+', 'A+'), ('AB+', 'AB+'), ('B-', 'B-'), ('O-', 'O-'), ('A', 'A'), ('B+', 'B+'), ('AB-', 'AB-')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='county',
            field=models.CharField(choices=[('Mombasa', 'Mombasa'), ('Samburu', 'Samburu'), ('Laikipia', 'Laikipia'), ('Uasin Gishu', 'Uasin Gishu'), ('Siaya', 'Siaya'), ('Lamu', 'Lamu'), ('Vihiga', 'Vihiga'), ('Tana River', 'Tana River'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Kwale', 'Kwale'), ('Mandera', 'Mandera'), ('Kitui', 'Kitui'), ('Makueni', 'Makueni'), ('Kisii', 'Kisii'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Baringo', 'Baringo'), ('Narok', 'Narok'), ('Embu', 'Embu'), ('Kilifi', 'Kilifi'), ('Nyandarua', 'Nyandarua'), ('Kisumu', 'Kisumu'), ('Nandi', 'Nandi'), ("Murang'a", "Murang'a"), ('Taita-Taveta', 'Taita-Taveta'), ('Bungoma', 'Bungoma'), ('Meru', 'Meru'), ('Kirinyaga', 'Kirinyaga'), ('Bomet', 'Bomet'), ('Kiambu', 'Kiambu'), ('Homa Bay', 'Homa Bay'), ('Machakos', 'Machakos'), ('Garissa', 'Garissa'), ('Isiolo', 'Homa Bay'), ('Kakamega', 'Kakamega'), ('Busia', 'Busia'), ('Kericho', 'Kericho'), ('Kajiado', 'Kajiado'), ('Trans Nzoia', 'Trans Nzoia'), ('Migori', 'Migori'), ('Nairobi', 'Nairobi'), ('Marsabit', 'Marsabit'), ('Turkana', 'Turkana'), ('Wajir', 'Wajir'), ('West Pokot', 'West Pokot'), ('Nyamira', 'Nyamira'), ('Nakuru', 'Nakuru'), ('Nyeri', 'Nyeri')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='donor',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 13, 52, 36, 526951)),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(default=uuid.UUID('f625e0c6-8572-48da-908e-a254421a17f7'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('A+', 'A+'), ('AB+', 'AB+'), ('B-', 'B-'), ('O-', 'O-'), ('A', 'A'), ('B+', 'B+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 13, 52, 36, 531947)),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 13, 52, 36, 528948)),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='pre_exam_id',
            field=models.CharField(default=uuid.UUID('8b3279bf-2d5c-45d1-b99f-d3f1b3ad06c9'), max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=8),
        ),
    ]
