# Generated by Django 4.2.3 on 2023-07-24 11:28

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0032_alter_blooddonate_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('B-', 'B-'), ('O+', 'O+'), ('AB+', 'AB+'), ('B+', 'B+'), ('O-', 'O-'), ('A+', 'A+'), ('AB-', 'AB-'), ('A', 'A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 14, 28, 3, 427107)),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='donation_id',
            field=models.CharField(default=uuid.UUID('07a755da-4a7e-4dd6-ab96-3550333c9936'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donationtype',
            name='type',
            field=models.CharField(choices=[('Plasma', 'Plasma'), ('Platelets', 'Platelets'), ('Power Red', 'Power Red'), ('Blood', 'Blood')], default='Blood', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('B-', 'B-'), ('O+', 'O+'), ('AB+', 'AB+'), ('B+', 'B+'), ('O-', 'O-'), ('A+', 'A+'), ('AB-', 'AB-'), ('A', 'A')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='county',
            field=models.CharField(choices=[('Tana River', 'Tana River'), ('Kisii', 'Kisii'), ('Kitui', 'Kitui'), ('Uasin Gishu', 'Uasin Gishu'), ('Kisumu', 'Kisumu'), ('Kericho', 'Kericho'), ('Nandi', 'Nandi'), ('Kajiado', 'Kajiado'), ('Kilifi', 'Kilifi'), ('Marsabit', 'Marsabit'), ('Nyeri', 'Nyeri'), ('Siaya', 'Siaya'), ('Turkana', 'Turkana'), ('Samburu', 'Samburu'), ('Kwale', 'Kwale'), ('Nyandarua', 'Nyandarua'), ('Kakamega', 'Kakamega'), ('Migori', 'Migori'), ('Baringo', 'Baringo'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Makueni', 'Makueni'), ('Busia', 'Busia'), ('Bungoma', 'Bungoma'), ('Lamu', 'Lamu'), ("Murang'a", "Murang'a"), ('Nakuru', 'Nakuru'), ('Mandera', 'Mandera'), ('Laikipia', 'Laikipia'), ('West Pokot', 'West Pokot'), ('Trans Nzoia', 'Trans Nzoia'), ('Kirinyaga', 'Kirinyaga'), ('Isiolo', 'Homa Bay'), ('Meru', 'Meru'), ('Wajir', 'Wajir'), ('Homa Bay', 'Homa Bay'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Embu', 'Embu'), ('Taita-Taveta', 'Taita-Taveta'), ('Mombasa', 'Mombasa'), ('Narok', 'Narok'), ('Vihiga', 'Vihiga'), ('Nairobi', 'Nairobi'), ('Machakos', 'Machakos'), ('Kiambu', 'Kiambu'), ('Bomet', 'Bomet'), ('Garissa', 'Garissa'), ('Nyamira', 'Nyamira')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='donor',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 14, 28, 3, 423111)),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(default=uuid.UUID('5c28a87d-dcfd-41a0-a801-974bc90f871d'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('B-', 'B-'), ('O+', 'O+'), ('AB+', 'AB+'), ('B+', 'B+'), ('O-', 'O-'), ('A+', 'A+'), ('AB-', 'AB-'), ('A', 'A')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F'), ('Nil', 'Nil')], default='Nil', max_length=3),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='attachment',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 14, 28, 3, 428106)),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 14, 28, 3, 425109)),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='pre_exam_id',
            field=models.CharField(default=uuid.UUID('fa32014a-4ca6-40d6-8bfd-0bc809ca5e0b'), max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Pending', max_length=8),
        ),
    ]
