# Generated by Django 4.2.3 on 2023-08-22 18:32

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0034_alter_blooddonate_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('B-', 'B-'), ('A+', 'A+'), ('B+', 'B+'), ('AB-', 'AB-'), ('A', 'A'), ('AB+', 'AB+')], max_length=3),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 21, 32, 51, 783697)),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='donation_id',
            field=models.CharField(default=uuid.UUID('d3364b44-4a95-4769-bd29-84eb191e5ee1'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donationtype',
            name='type',
            field=models.CharField(choices=[('Power Red', 'Power Red'), ('Plasma', 'Plasma'), ('Platelets', 'Platelets'), ('Blood', 'Blood')], default='Blood', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('B-', 'B-'), ('A+', 'A+'), ('B+', 'B+'), ('AB-', 'AB-'), ('A', 'A'), ('AB+', 'AB+')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='county',
            field=models.CharField(choices=[('Homa Bay', 'Homa Bay'), ("Murang'a", "Murang'a"), ('Wajir', 'Wajir'), ('Nyandarua', 'Nyandarua'), ('Turkana', 'Turkana'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kilifi', 'Kilifi'), ('Kisii', 'Kisii'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Makueni', 'Makueni'), ('Tana River', 'Tana River'), ('Kirinyaga', 'Kirinyaga'), ('Migori', 'Migori'), ('Nyeri', 'Nyeri'), ('Busia', 'Busia'), ('Nakuru', 'Nakuru'), ('Nairobi', 'Nairobi'), ('Mandera', 'Mandera'), ('Siaya', 'Siaya'), ('Trans Nzoia', 'Trans Nzoia'), ('Marsabit', 'Marsabit'), ('Isiolo', 'Homa Bay'), ('Bomet', 'Bomet'), ('Machakos', 'Machakos'), ('Kisumu', 'Kisumu'), ('Uasin Gishu', 'Uasin Gishu'), ('Vihiga', 'Vihiga'), ('Baringo', 'Baringo'), ('Meru', 'Meru'), ('Samburu', 'Samburu'), ('Nyamira', 'Nyamira'), ('Kiambu', 'Kiambu'), ('Nandi', 'Nandi'), ('West Pokot', 'West Pokot'), ('Taita-Taveta', 'Taita-Taveta'), ('Kericho', 'Kericho'), ('Narok', 'Narok'), ('Garissa', 'Garissa'), ('Kajiado', 'Kajiado'), ('Kakamega', 'Kakamega'), ('Lamu', 'Lamu'), ('Kitui', 'Kitui'), ('Kwale', 'Kwale'), ('Laikipia', 'Laikipia'), ('Embu', 'Embu'), ('Mombasa', 'Mombasa'), ('Bungoma', 'Bungoma')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='donor',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 21, 32, 51, 778701)),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(default=uuid.UUID('89eae6ae-233d-4a7d-b677-bf7847ebf72d'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('B-', 'B-'), ('A+', 'A+'), ('B+', 'B+'), ('AB-', 'AB-'), ('A', 'A'), ('AB+', 'AB+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='gender',
            field=models.CharField(choices=[('F', 'F'), ('Nil', 'Nil'), ('M', 'M')], default='Nil', max_length=3),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 21, 32, 51, 784696)),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 21, 32, 51, 781700)),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='pre_exam_id',
            field=models.CharField(default=uuid.UUID('8047a919-7ecb-4f58-98d6-61ae4e9c8243'), max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=8),
        ),
    ]
