# Generated by Django 4.2.3 on 2023-08-23 08:45

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0035_alter_blooddonate_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('B+', 'B+'), ('O-', 'O-'), ('B-', 'B-'), ('A+', 'A+'), ('A', 'A'), ('AB+', 'AB+'), ('O+', 'O+'), ('AB-', 'AB-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 11, 45, 20, 766220)),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='donation_id',
            field=models.CharField(default=uuid.UUID('2521e757-c828-41a9-a53f-c0c5d4d2e593'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donationtype',
            name='type',
            field=models.CharField(choices=[('Plasma', 'Plasma'), ('Blood', 'Blood'), ('Power Red', 'Power Red'), ('Platelets', 'Platelets')], default='Blood', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('B+', 'B+'), ('O-', 'O-'), ('B-', 'B-'), ('A+', 'A+'), ('A', 'A'), ('AB+', 'AB+'), ('O+', 'O+'), ('AB-', 'AB-')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='county',
            field=models.CharField(choices=[('Nakuru', 'Nakuru'), ('Kwale', 'Kwale'), ('Kakamega', 'Kakamega'), ('Lamu', 'Lamu'), ('Baringo', 'Baringo'), ('Nairobi', 'Nairobi'), ('Laikipia', 'Laikipia'), ('Garissa', 'Garissa'), ('Tana River', 'Tana River'), ('Meru', 'Meru'), ('Embu', 'Embu'), ('Narok', 'Narok'), ('Nyamira', 'Nyamira'), ('Kisumu', 'Kisumu'), ("Murang'a", "Murang'a"), ('Bomet', 'Bomet'), ('Mandera', 'Mandera'), ('Taita-Taveta', 'Taita-Taveta'), ('Nyandarua', 'Nyandarua'), ('Nandi', 'Nandi'), ('Busia', 'Busia'), ('Machakos', 'Machakos'), ('Bungoma', 'Bungoma'), ('Isiolo', 'Homa Bay'), ('Vihiga', 'Vihiga'), ('Homa Bay', 'Homa Bay'), ('Kericho', 'Kericho'), ('Samburu', 'Samburu'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Kirinyaga', 'Kirinyaga'), ('Marsabit', 'Marsabit'), ('Siaya', 'Siaya'), ('Kisii', 'Kisii'), ('Uasin Gishu', 'Uasin Gishu'), ('West Pokot', 'West Pokot'), ('Kiambu', 'Kiambu'), ('Mombasa', 'Mombasa'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Wajir', 'Wajir'), ('Kitui', 'Kitui'), ('Nyeri', 'Nyeri'), ('Turkana', 'Turkana'), ('Trans Nzoia', 'Trans Nzoia'), ('Kajiado', 'Kajiado'), ('Kilifi', 'Kilifi'), ('Migori', 'Migori'), ('Makueni', 'Makueni')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='donor',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 11, 45, 20, 760222)),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(default=uuid.UUID('5380d535-ef7a-45d6-9510-f66280624d61'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('B+', 'B+'), ('O-', 'O-'), ('B-', 'B-'), ('A+', 'A+'), ('A', 'A'), ('AB+', 'AB+'), ('O+', 'O+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donorhealthinfo',
            name='gender',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M'), ('Nil', 'Nil')], default='Nil', max_length=3),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 11, 45, 20, 767219)),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 11, 45, 20, 762223)),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='pre_exam_id',
            field=models.CharField(default=uuid.UUID('c0e101dc-0a5c-4ae0-a6af-093bd0cb0abb'), max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preexaminfo',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=8),
        ),
    ]
