# Generated by Django 3.0.5 on 2023-07-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
