# Generated by Django 4.2.3 on 2023-07-17 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('9d0f5a08-cb38-4b8f-8c1d-b810e87a1e1a'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donationreport',
            name='station_id',
            field=models.CharField(default='x', max_length=50, null=True),
        ),
    ]
