# Generated by Django 4.2.3 on 2023-07-17 11:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0031_alter_hostedblooddrives_county_and_more'),
        ('volunteer', '0002_alter_donationreport_report_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('c99bc978-3f72-4c18-b365-70e42a4e0362'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='DonorReport',
            fields=[
                ('report_id', models.CharField(default=uuid.UUID('b8e7828c-315f-44cb-ab51-2c2c1f5e097a'), max_length=50, primary_key=True, serialize=False)),
                ('station_id', models.CharField(default='x', max_length=50, null=True)),
                ('title', models.CharField(default='Donation-report', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField()),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.volunteerregistration')),
            ],
        ),
    ]
