# Generated by Django 4.2.3 on 2023-07-17 17:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_alter_donationreport_report_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('3e98ad67-3be1-4448-b8b3-cd79c1224056'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donorreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('b8a6abe1-c0f9-46f1-a2b6-83fac61289b3'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('9fc6f86e-c06d-43d5-8945-f420c71ca1b5'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
