# Generated by Django 4.2.3 on 2023-07-17 17:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_alter_donationreport_report_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('b6f3cf67-59a4-42f0-81c2-de8984097552'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donorreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('b0c554e3-5358-455c-aa21-5a4cbd998ddc'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('ec86af20-0cc0-4371-9ce8-0fbf3e09ff42'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
