# Generated by Django 4.2.3 on 2023-07-17 17:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0006_alter_donationreport_report_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('b14144bb-f92b-4585-8be7-e024b193e9b8'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donorreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('275c8d35-8e98-4017-abac-a78a03d7c48a'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('09e0422a-b482-49cd-952e-0fb82c6b7cad'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
