# Generated by Django 4.2.3 on 2023-07-17 20:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0007_alter_donationreport_report_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('982d4874-6dc9-46b4-8a0e-5f3c08ea96ea'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donorreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('b26e003c-a8d1-4580-9442-bc2b539730b3'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('b7158cda-eb05-4acb-8865-a258bc93d3d3'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
