# Generated by Django 4.2.3 on 2023-07-17 20:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0008_alter_donationreport_report_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('fa924c75-9936-4dcf-ac5c-f834aba0b8b1'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donorreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('87ab1cba-04c6-4277-9262-89a81a8f75c8'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('0fe9f1e1-8a26-42c3-87e4-f29f427f49a4'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
