# Generated by Django 4.2.3 on 2023-07-18 11:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0009_alter_donationreport_report_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('d4dae2c9-bf64-45e2-8f3e-0f23643bc9b3'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donorreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('d2351790-7314-4226-a82f-2a09f49795c4'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('721e8ae6-62df-450c-bf46-90f3a7b74a8d'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
