# Generated by Django 4.2.3 on 2023-07-20 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0010_alter_donationreport_report_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('f6c73f08-a63b-4841-a4d7-e212a43dcfc3'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donorreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('cab8de85-554b-4462-9a09-de2febac8afa'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('c5d1a977-cdee-4592-94ea-1bff8593566d'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
