# Generated by Django 4.2.3 on 2023-07-24 04:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0012_alter_donationreport_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('5e881d01-e025-4214-9c0c-552d3e7b02da'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donorreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('0cc4ce94-d96e-4239-af6b-1731bfe5b0f6'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('7b490388-ab08-4c94-a83c-9e5d16e8e624'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
