# Generated by Django 4.2.3 on 2023-07-24 06:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0013_alter_donationreport_report_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('c894f180-b891-4562-ba04-9e69f84b70dd'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donorreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('d63dab8c-91db-4e52-8747-f1d0e54aa76f'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('f96fd30d-1918-4bcb-9674-b8741578d6f3'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
