# Generated by Django 4.2.3 on 2023-07-24 10:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0032_alter_blooddonate_blood_group_and_more'),
        ('volunteer', '0014_alter_donationreport_report_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('412d0967-4469-4270-acf3-4e4c1b894020'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donorreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('1bb95487-64d1-4412-b432-be72f3e5430d'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('c937aa0f-8b98-4418-9790-dd0ddb79ce73'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PreExamsReport',
            fields=[
                ('report_id', models.CharField(default=uuid.UUID('d93900d2-7ec0-4091-af9f-5b85df50b22f'), max_length=50, primary_key=True, serialize=False)),
                ('station_id', models.CharField(default='x', max_length=50, null=True)),
                ('title', models.CharField(default='Donation-report', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/pre-exam-reports/')),
                ('created_at', models.DateTimeField()),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donor')),
            ],
        ),
    ]
