# Generated by Django 4.2.3 on 2023-08-19 18:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0017_alter_donationreport_report_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('5b9b10fb-1985-4839-b894-741d488feca7'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donorreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('fb088e77-2536-4886-8cf9-88299d461c77'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preexamsreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('c35b8b1b-2d7e-4f78-b5ef-86d5de0d543f'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('cfa988f9-5974-4c66-916c-2865798eabe8'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
