# Generated by Django 4.2.3 on 2023-08-22 18:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0018_alter_donationreport_report_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('766f3ec0-d765-4dab-bd95-c1e6f02eda5a'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donorreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('1f181bd5-1c9e-48a7-9c7e-19947fc5de8a'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preexamsreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('5d1e9d89-a57b-49cc-af84-d5c6d48d8fcb'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('547edb3f-cf01-4c8e-8376-82807c84aee9'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
