# Generated by Django 4.2.3 on 2023-08-23 08:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0019_alter_donationreport_report_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('8cb050cc-c8c3-4311-b9e1-68a83c4dc567'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donorreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('0c7237e1-0db8-4f7c-9f92-38e5548ad34d'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preexamsreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('d6197b24-8790-4071-a240-0882812862e2'), max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='report_id',
            field=models.CharField(default=uuid.UUID('977b901d-2d49-4b9c-a18d-c75ff8f2e3f1'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
