# Generated by Django 3.0.5 on 2023-07-12 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('location', models.CharField(choices=[('Marsabit', 'Marsabit'), ('Kisumu', 'Kisumu'), ('Nyeri', 'Nyeri'), ('Busia', 'Busia'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Trans Nzoia', 'Trans Nzoia'), ('Turkana', 'Turkana'), ('Taita-Taveta', 'Taita-Taveta'), ('Meru', 'Meru'), ('Vihiga', 'Vihiga'), ('Kwale', 'Kwale'), ('Makueni', 'Makueni'), ('Uasin Gishu', 'Uasin Gishu'), ('Mombasa', 'Mombasa'), ('Embu', 'Embu'), ('Nandi', 'Nandi'), ('Wajir', 'Wajir'), ('Nyandarua', 'Nyandarua'), ('Isiolo', 'Homa Bay'), ('Lamu', 'Lamu'), ('Nairobi', 'Nairobi'), ('Kitui', 'Kitui'), ('West Pokot', 'West Pokot'), ('Kericho', 'Kericho'), ('Kiambu', 'Kiambu'), ('Machakos', 'Machakos'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Nakuru', 'Nakuru'), ('Migori', 'Migori'), ('Mandera', 'Mandera'), ('Laikipia', 'Laikipia'), ('Narok', 'Narok'), ('Kakamega', 'Kakamega'), ('Bomet', 'Bomet'), ('Kilifi', 'Kilifi'), ('Kirinyaga', 'Kirinyaga'), ('Baringo', 'Baringo'), ('Tana River', 'Tana River'), ('Bungoma', 'Bungoma'), ('Kisii', 'Kisii'), ('Garissa', 'Garissa'), ("Murang'a", 'Murang'), ('Nyamira', 'Nyamira'), ('Siaya', 'Siaya'), ('Homa Bay', 'Homa Bay'), ('Samburu', 'Samburu'), ('Kajiado', 'Kajiado')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Available', 'Available'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
