# Generated by Django 3.0.5 on 2023-07-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20230712_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerregistration',
            name='reason',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Vihiga', 'Vihiga'), ('Isiolo', 'Homa Bay'), ('Embu', 'Embu'), ('Wajir', 'Wajir'), ('Nyamira', 'Nyamira'), ('Narok', 'Narok'), ('Taita-Taveta', 'Taita-Taveta'), ('Turkana', 'Turkana'), ('Migori', 'Migori'), ('Marsabit', 'Marsabit'), ('Nyandarua', 'Nyandarua'), ('Kwale', 'Kwale'), ("Murang'a", 'Murang'), ('Kirinyaga', 'Kirinyaga'), ('Kitui', 'Kitui'), ('Siaya', 'Siaya'), ('Garissa', 'Garissa'), ('Machakos', 'Machakos'), ('Uasin Gishu', 'Uasin Gishu'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Kisumu', 'Kisumu'), ('Nandi', 'Nandi'), ('West Pokot', 'West Pokot'), ('Kisii', 'Kisii'), ('Nakuru', 'Nakuru'), ('Meru', 'Meru'), ('Mandera', 'Mandera'), ('Kiambu', 'Kiambu'), ('Bomet', 'Bomet'), ('Trans Nzoia', 'Trans Nzoia'), ('Makueni', 'Makueni'), ('Kilifi', 'Kilifi'), ('Baringo', 'Baringo'), ('Laikipia', 'Laikipia'), ('Samburu', 'Samburu'), ('Nyeri', 'Nyeri'), ('Homa Bay', 'Homa Bay'), ('Bungoma', 'Bungoma'), ('Kajiado', 'Kajiado'), ('Tana River', 'Tana River'), ('Kericho', 'Kericho'), ('Kakamega', 'Kakamega'), ('Mombasa', 'Mombasa'), ('Lamu', 'Lamu'), ('Busia', 'Busia'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Nairobi', 'Nairobi')], max_length=100),
        ),
    ]
