# Generated by Django 3.0.5 on 2023-07-13 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20230713_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostedBloodDrives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('attendees', models.PositiveIntegerField(max_length=100)),
                ('phone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=40)),
                ('county', models.CharField(choices=[('Busia', 'Busia'), ('Trans Nzoia', 'Trans Nzoia'), ("Murang'a", 'Murang'), ('Kajiado', 'Kajiado'), ('Tana River', 'Tana River'), ('Nyandarua', 'Nyandarua'), ('Bomet', 'Bomet'), ('Narok', 'Narok'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Bungoma', 'Bungoma'), ('Taita-Taveta', 'Taita-Taveta'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Baringo', 'Baringo'), ('Kakamega', 'Kakamega'), ('Nandi', 'Nandi'), ('Marsabit', 'Marsabit'), ('Embu', 'Embu'), ('Lamu', 'Lamu'), ('West Pokot', 'West Pokot'), ('Kwale', 'Kwale'), ('Wajir', 'Wajir'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Makueni', 'Makueni'), ('Homa Bay', 'Homa Bay'), ('Kilifi', 'Kilifi'), ('Kisii', 'Kisii'), ('Uasin Gishu', 'Uasin Gishu'), ('Kericho', 'Kericho'), ('Laikipia', 'Laikipia'), ('Vihiga', 'Vihiga'), ('Nairobi', 'Nairobi'), ('Machakos', 'Machakos'), ('Nakuru', 'Nakuru'), ('Kitui', 'Kitui'), ('Kirinyaga', 'Kirinyaga'), ('Isiolo', 'Homa Bay'), ('Nyamira', 'Nyamira'), ('Migori', 'Migori'), ('Garissa', 'Garissa'), ('Siaya', 'Siaya'), ('Meru', 'Meru'), ('Nyeri', 'Nyeri'), ('Kiambu', 'Kiambu'), ('Turkana', 'Turkana'), ('Mandera', 'Mandera'), ('Samburu', 'Samburu')], max_length=15)),
                ('date', models.DateField()),
                ('plan_doc', models.FileField(upload_to='hosted_blood_drives/<built-in function id>/')),
            ],
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Busia', 'Busia'), ('Trans Nzoia', 'Trans Nzoia'), ("Murang'a", 'Murang'), ('Kajiado', 'Kajiado'), ('Tana River', 'Tana River'), ('Nyandarua', 'Nyandarua'), ('Bomet', 'Bomet'), ('Narok', 'Narok'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Bungoma', 'Bungoma'), ('Taita-Taveta', 'Taita-Taveta'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Baringo', 'Baringo'), ('Kakamega', 'Kakamega'), ('Nandi', 'Nandi'), ('Marsabit', 'Marsabit'), ('Embu', 'Embu'), ('Lamu', 'Lamu'), ('West Pokot', 'West Pokot'), ('Kwale', 'Kwale'), ('Wajir', 'Wajir'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Makueni', 'Makueni'), ('Homa Bay', 'Homa Bay'), ('Kilifi', 'Kilifi'), ('Kisii', 'Kisii'), ('Uasin Gishu', 'Uasin Gishu'), ('Kericho', 'Kericho'), ('Laikipia', 'Laikipia'), ('Vihiga', 'Vihiga'), ('Nairobi', 'Nairobi'), ('Machakos', 'Machakos'), ('Nakuru', 'Nakuru'), ('Kitui', 'Kitui'), ('Kirinyaga', 'Kirinyaga'), ('Isiolo', 'Homa Bay'), ('Nyamira', 'Nyamira'), ('Migori', 'Migori'), ('Garissa', 'Garissa'), ('Siaya', 'Siaya'), ('Meru', 'Meru'), ('Nyeri', 'Nyeri'), ('Kiambu', 'Kiambu'), ('Turkana', 'Turkana'), ('Mandera', 'Mandera'), ('Samburu', 'Samburu')], max_length=100),
        ),
    ]
