# Generated by Django 3.0.5 on 2023-07-15 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0013_auto_20230715_1241'),
        ('appointments', '0011_auto_20230715_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerregistration',
            name='blood_drive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blood.BloodDrives'),
        ),
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Siaya', 'Siaya'), ('Makueni', 'Makueni'), ('Kericho', 'Kericho'), ('Embu', 'Embu'), ('Mombasa', 'Mombasa'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Garissa', 'Garissa'), ('Mandera', 'Mandera'), ('Bungoma', 'Bungoma'), ('Wajir', 'Wajir'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Laikipia', 'Laikipia'), ('Nyandarua', 'Nyandarua'), ('Marsabit', 'Marsabit'), ('Kisii', 'Kisii'), ('Kajiado', 'Kajiado'), ('Migori', 'Migori'), ('Kakamega', 'Kakamega'), ('Meru', 'Meru'), ('Isiolo', 'Homa Bay'), ('West Pokot', 'West Pokot'), ('Baringo', 'Baringo'), ('Kiambu', 'Kiambu'), ('Machakos', 'Machakos'), ('Vihiga', 'Vihiga'), ('Kisumu', 'Kisumu'), ('Busia', 'Busia'), ('Nyeri', 'Nyeri'), ('Kilifi', 'Kilifi'), ('Uasin Gishu', 'Uasin Gishu'), ('Kwale', 'Kwale'), ('Kitui', 'Kitui'), ('Bomet', 'Bomet'), ('Samburu', 'Samburu'), ('Narok', 'Narok'), ('Kirinyaga', 'Kirinyaga'), ("Murang'a", 'Murang'), ('Lamu', 'Lamu'), ('Homa Bay', 'Homa Bay'), ('Tana River', 'Tana River'), ('Nairobi', 'Nairobi'), ('Trans Nzoia', 'Trans Nzoia'), ('Nakuru', 'Nakuru'), ('Turkana', 'Turkana'), ('Nyamira', 'Nyamira'), ('Nandi', 'Nandi'), ('Taita-Taveta', 'Taita-Taveta')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Siaya', 'Siaya'), ('Makueni', 'Makueni'), ('Kericho', 'Kericho'), ('Embu', 'Embu'), ('Mombasa', 'Mombasa'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Garissa', 'Garissa'), ('Mandera', 'Mandera'), ('Bungoma', 'Bungoma'), ('Wajir', 'Wajir'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Laikipia', 'Laikipia'), ('Nyandarua', 'Nyandarua'), ('Marsabit', 'Marsabit'), ('Kisii', 'Kisii'), ('Kajiado', 'Kajiado'), ('Migori', 'Migori'), ('Kakamega', 'Kakamega'), ('Meru', 'Meru'), ('Isiolo', 'Homa Bay'), ('West Pokot', 'West Pokot'), ('Baringo', 'Baringo'), ('Kiambu', 'Kiambu'), ('Machakos', 'Machakos'), ('Vihiga', 'Vihiga'), ('Kisumu', 'Kisumu'), ('Busia', 'Busia'), ('Nyeri', 'Nyeri'), ('Kilifi', 'Kilifi'), ('Uasin Gishu', 'Uasin Gishu'), ('Kwale', 'Kwale'), ('Kitui', 'Kitui'), ('Bomet', 'Bomet'), ('Samburu', 'Samburu'), ('Narok', 'Narok'), ('Kirinyaga', 'Kirinyaga'), ("Murang'a", 'Murang'), ('Lamu', 'Lamu'), ('Homa Bay', 'Homa Bay'), ('Tana River', 'Tana River'), ('Nairobi', 'Nairobi'), ('Trans Nzoia', 'Trans Nzoia'), ('Nakuru', 'Nakuru'), ('Turkana', 'Turkana'), ('Nyamira', 'Nyamira'), ('Nandi', 'Nandi'), ('Taita-Taveta', 'Taita-Taveta')], max_length=100),
        ),
    ]
