# Generated by Django 3.0.5 on 2023-07-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_auto_20230715_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Kiambu', 'Kiambu'), ('Busia', 'Busia'), ('Isiolo', 'Homa Bay'), ('Turkana', 'Turkana'), ('Trans Nzoia', 'Trans Nzoia'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Kilifi', 'Kilifi'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kisii', 'Kisii'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Narok', 'Narok'), ('Marsabit', 'Marsabit'), ('Kwale', 'Kwale'), ('Nyamira', 'Nyamira'), ('Laikipia', 'Laikipia'), ('Kakamega', 'Kakamega'), ('Bomet', 'Bomet'), ('West Pokot', 'West Pokot'), ('Kisumu', 'Kisumu'), ('Nakuru', 'Nakuru'), ('Migori', 'Migori'), ('Nyeri', 'Nyeri'), ('Mandera', 'Mandera'), ('Siaya', 'Siaya'), ('Uasin Gishu', 'Uasin Gishu'), ("Murang'a", 'Murang'), ('Lamu', 'Lamu'), ('Embu', 'Embu'), ('Samburu', 'Samburu'), ('Homa Bay', 'Homa Bay'), ('Kajiado', 'Kajiado'), ('Kirinyaga', 'Kirinyaga'), ('Kitui', 'Kitui'), ('Kericho', 'Kericho'), ('Bungoma', 'Bungoma'), ('Meru', 'Meru'), ('Mombasa', 'Mombasa'), ('Nyandarua', 'Nyandarua'), ('Baringo', 'Baringo'), ('Tana River', 'Tana River'), ('Nandi', 'Nandi'), ('Taita-Taveta', 'Taita-Taveta'), ('Vihiga', 'Vihiga'), ('Garissa', 'Garissa'), ('Nairobi', 'Nairobi'), ('Wajir', 'Wajir')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Kiambu', 'Kiambu'), ('Busia', 'Busia'), ('Isiolo', 'Homa Bay'), ('Turkana', 'Turkana'), ('Trans Nzoia', 'Trans Nzoia'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Kilifi', 'Kilifi'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kisii', 'Kisii'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Narok', 'Narok'), ('Marsabit', 'Marsabit'), ('Kwale', 'Kwale'), ('Nyamira', 'Nyamira'), ('Laikipia', 'Laikipia'), ('Kakamega', 'Kakamega'), ('Bomet', 'Bomet'), ('West Pokot', 'West Pokot'), ('Kisumu', 'Kisumu'), ('Nakuru', 'Nakuru'), ('Migori', 'Migori'), ('Nyeri', 'Nyeri'), ('Mandera', 'Mandera'), ('Siaya', 'Siaya'), ('Uasin Gishu', 'Uasin Gishu'), ("Murang'a", 'Murang'), ('Lamu', 'Lamu'), ('Embu', 'Embu'), ('Samburu', 'Samburu'), ('Homa Bay', 'Homa Bay'), ('Kajiado', 'Kajiado'), ('Kirinyaga', 'Kirinyaga'), ('Kitui', 'Kitui'), ('Kericho', 'Kericho'), ('Bungoma', 'Bungoma'), ('Meru', 'Meru'), ('Mombasa', 'Mombasa'), ('Nyandarua', 'Nyandarua'), ('Baringo', 'Baringo'), ('Tana River', 'Tana River'), ('Nandi', 'Nandi'), ('Taita-Taveta', 'Taita-Taveta'), ('Vihiga', 'Vihiga'), ('Garissa', 'Garissa'), ('Nairobi', 'Nairobi'), ('Wajir', 'Wajir')], max_length=100),
        ),
    ]
