# Generated by Django 3.0.5 on 2023-07-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_auto_20230715_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Tharaka-Nithi', 'Tharaka-Nithi'), ('Baringo', 'Baringo'), ('Isiolo', 'Homa Bay'), ('Taita-Taveta', 'Taita-Taveta'), ('Machakos', 'Machakos'), ('Samburu', 'Samburu'), ('Kisumu', 'Kisumu'), ('Busia', 'Busia'), ('Nyamira', 'Nyamira'), ('Garissa', 'Garissa'), ('Turkana', 'Turkana'), ('Trans Nzoia', 'Trans Nzoia'), ('Mandera', 'Mandera'), ('Tana River', 'Tana River'), ('Laikipia', 'Laikipia'), ('Kiambu', 'Kiambu'), ('Nakuru', 'Nakuru'), ('Mombasa', 'Mombasa'), ('West Pokot', 'West Pokot'), ('Kilifi', 'Kilifi'), ('Lamu', 'Lamu'), ('Marsabit', 'Marsabit'), ('Kirinyaga', 'Kirinyaga'), ('Narok', 'Narok'), ('Homa Bay', 'Homa Bay'), ('Bomet', 'Bomet'), ('Vihiga', 'Vihiga'), ('Nyeri', 'Nyeri'), ('Kitui', 'Kitui'), ('Wajir', 'Wajir'), ('Kisii', 'Kisii'), ('Nandi', 'Nandi'), ('Embu', 'Embu'), ('Uasin Gishu', 'Uasin Gishu'), ('Kericho', 'Kericho'), ('Makueni', 'Makueni'), ('Bungoma', 'Bungoma'), ('Kajiado', 'Kajiado'), ('Siaya', 'Siaya'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Kwale', 'Kwale'), ('Meru', 'Meru'), ('Migori', 'Migori'), ('Kakamega', 'Kakamega'), ('Nyandarua', 'Nyandarua'), ('Nairobi', 'Nairobi'), ("Murang'a", 'Murang')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Tharaka-Nithi', 'Tharaka-Nithi'), ('Baringo', 'Baringo'), ('Isiolo', 'Homa Bay'), ('Taita-Taveta', 'Taita-Taveta'), ('Machakos', 'Machakos'), ('Samburu', 'Samburu'), ('Kisumu', 'Kisumu'), ('Busia', 'Busia'), ('Nyamira', 'Nyamira'), ('Garissa', 'Garissa'), ('Turkana', 'Turkana'), ('Trans Nzoia', 'Trans Nzoia'), ('Mandera', 'Mandera'), ('Tana River', 'Tana River'), ('Laikipia', 'Laikipia'), ('Kiambu', 'Kiambu'), ('Nakuru', 'Nakuru'), ('Mombasa', 'Mombasa'), ('West Pokot', 'West Pokot'), ('Kilifi', 'Kilifi'), ('Lamu', 'Lamu'), ('Marsabit', 'Marsabit'), ('Kirinyaga', 'Kirinyaga'), ('Narok', 'Narok'), ('Homa Bay', 'Homa Bay'), ('Bomet', 'Bomet'), ('Vihiga', 'Vihiga'), ('Nyeri', 'Nyeri'), ('Kitui', 'Kitui'), ('Wajir', 'Wajir'), ('Kisii', 'Kisii'), ('Nandi', 'Nandi'), ('Embu', 'Embu'), ('Uasin Gishu', 'Uasin Gishu'), ('Kericho', 'Kericho'), ('Makueni', 'Makueni'), ('Bungoma', 'Bungoma'), ('Kajiado', 'Kajiado'), ('Siaya', 'Siaya'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Kwale', 'Kwale'), ('Meru', 'Meru'), ('Migori', 'Migori'), ('Kakamega', 'Kakamega'), ('Nyandarua', 'Nyandarua'), ('Nairobi', 'Nairobi'), ("Murang'a", 'Murang')], max_length=100),
        ),
    ]
