# Generated by Django 3.0.5 on 2023-07-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_auto_20230715_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Meru', 'Meru'), ('Lamu', 'Lamu'), ('Nyandarua', 'Nyandarua'), ('Turkana', 'Turkana'), ('Kisii', 'Kisii'), ('Machakos', 'Machakos'), ('Migori', 'Migori'), ('Kirinyaga', 'Kirinyaga'), ('Nakuru', 'Nakuru'), ('Marsabit', 'Marsabit'), ('Bungoma', 'Bungoma'), ('Trans Nzoia', 'Trans Nzoia'), ('Kisumu', 'Kisumu'), ('Wajir', 'Wajir'), ('Kitui', 'Kitui'), ('Baringo', 'Baringo'), ('Nandi', 'Nandi'), ('Mandera', 'Mandera'), ('Tana River', 'Tana River'), ('Kericho', 'Kericho'), ('Kwale', 'Kwale'), ('Siaya', 'Siaya'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Makueni', 'Makueni'), ('Homa Bay', 'Homa Bay'), ('Busia', 'Busia'), ('Kakamega', 'Kakamega'), ('Narok', 'Narok'), ('Vihiga', 'Vihiga'), ('Uasin Gishu', 'Uasin Gishu'), ('Kiambu', 'Kiambu'), ('Kilifi', 'Kilifi'), ('Nyamira', 'Nyamira'), ('Samburu', 'Samburu'), ('Embu', 'Embu'), ('Nyeri', 'Nyeri'), ('Taita-Taveta', 'Taita-Taveta'), ('Mombasa', 'Mombasa'), ('Nairobi', 'Nairobi'), ("Murang'a", 'Murang'), ('Laikipia', 'Laikipia'), ('Kajiado', 'Kajiado'), ('West Pokot', 'West Pokot'), ('Isiolo', 'Homa Bay'), ('Garissa', 'Garissa'), ('Bomet', 'Bomet')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Meru', 'Meru'), ('Lamu', 'Lamu'), ('Nyandarua', 'Nyandarua'), ('Turkana', 'Turkana'), ('Kisii', 'Kisii'), ('Machakos', 'Machakos'), ('Migori', 'Migori'), ('Kirinyaga', 'Kirinyaga'), ('Nakuru', 'Nakuru'), ('Marsabit', 'Marsabit'), ('Bungoma', 'Bungoma'), ('Trans Nzoia', 'Trans Nzoia'), ('Kisumu', 'Kisumu'), ('Wajir', 'Wajir'), ('Kitui', 'Kitui'), ('Baringo', 'Baringo'), ('Nandi', 'Nandi'), ('Mandera', 'Mandera'), ('Tana River', 'Tana River'), ('Kericho', 'Kericho'), ('Kwale', 'Kwale'), ('Siaya', 'Siaya'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Makueni', 'Makueni'), ('Homa Bay', 'Homa Bay'), ('Busia', 'Busia'), ('Kakamega', 'Kakamega'), ('Narok', 'Narok'), ('Vihiga', 'Vihiga'), ('Uasin Gishu', 'Uasin Gishu'), ('Kiambu', 'Kiambu'), ('Kilifi', 'Kilifi'), ('Nyamira', 'Nyamira'), ('Samburu', 'Samburu'), ('Embu', 'Embu'), ('Nyeri', 'Nyeri'), ('Taita-Taveta', 'Taita-Taveta'), ('Mombasa', 'Mombasa'), ('Nairobi', 'Nairobi'), ("Murang'a", 'Murang'), ('Laikipia', 'Laikipia'), ('Kajiado', 'Kajiado'), ('West Pokot', 'West Pokot'), ('Isiolo', 'Homa Bay'), ('Garissa', 'Garissa'), ('Bomet', 'Bomet')], max_length=100),
        ),
    ]
