# Generated by Django 3.0.5 on 2023-07-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0017_auto_20230715_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Turkana', 'Turkana'), ('Uasin Gishu', 'Uasin Gishu'), ('Kiambu', 'Kiambu'), ('Migori', 'Migori'), ('Samburu', 'Samburu'), ('Embu', 'Embu'), ('Baringo', 'Baringo'), ('Nandi', 'Nandi'), ('Laikipia', 'Laikipia'), ('Nyamira', 'Nyamira'), ('Homa Bay', 'Homa Bay'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Taita-Taveta', 'Taita-Taveta'), ('Marsabit', 'Marsabit'), ('Meru', 'Meru'), ('Nairobi', 'Nairobi'), ('Wajir', 'Wajir'), ("Murang'a", 'Murang'), ('Kajiado', 'Kajiado'), ('Makueni', 'Makueni'), ('Isiolo', 'Homa Bay'), ('Machakos', 'Machakos'), ('Nyeri', 'Nyeri'), ('Nyandarua', 'Nyandarua'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Kitui', 'Kitui'), ('Narok', 'Narok'), ('Garissa', 'Garissa'), ('Vihiga', 'Vihiga'), ('Bomet', 'Bomet'), ('Trans Nzoia', 'Trans Nzoia'), ('Kericho', 'Kericho'), ('Kirinyaga', 'Kirinyaga'), ('Busia', 'Busia'), ('West Pokot', 'West Pokot'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kilifi', 'Kilifi'), ('Kisii', 'Kisii'), ('Lamu', 'Lamu'), ('Kakamega', 'Kakamega'), ('Kwale', 'Kwale'), ('Mandera', 'Mandera'), ('Siaya', 'Siaya'), ('Nakuru', 'Nakuru'), ('Bungoma', 'Bungoma'), ('Tana River', 'Tana River')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Turkana', 'Turkana'), ('Uasin Gishu', 'Uasin Gishu'), ('Kiambu', 'Kiambu'), ('Migori', 'Migori'), ('Samburu', 'Samburu'), ('Embu', 'Embu'), ('Baringo', 'Baringo'), ('Nandi', 'Nandi'), ('Laikipia', 'Laikipia'), ('Nyamira', 'Nyamira'), ('Homa Bay', 'Homa Bay'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Taita-Taveta', 'Taita-Taveta'), ('Marsabit', 'Marsabit'), ('Meru', 'Meru'), ('Nairobi', 'Nairobi'), ('Wajir', 'Wajir'), ("Murang'a", 'Murang'), ('Kajiado', 'Kajiado'), ('Makueni', 'Makueni'), ('Isiolo', 'Homa Bay'), ('Machakos', 'Machakos'), ('Nyeri', 'Nyeri'), ('Nyandarua', 'Nyandarua'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Kitui', 'Kitui'), ('Narok', 'Narok'), ('Garissa', 'Garissa'), ('Vihiga', 'Vihiga'), ('Bomet', 'Bomet'), ('Trans Nzoia', 'Trans Nzoia'), ('Kericho', 'Kericho'), ('Kirinyaga', 'Kirinyaga'), ('Busia', 'Busia'), ('West Pokot', 'West Pokot'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kilifi', 'Kilifi'), ('Kisii', 'Kisii'), ('Lamu', 'Lamu'), ('Kakamega', 'Kakamega'), ('Kwale', 'Kwale'), ('Mandera', 'Mandera'), ('Siaya', 'Siaya'), ('Nakuru', 'Nakuru'), ('Bungoma', 'Bungoma'), ('Tana River', 'Tana River')], max_length=100),
        ),
    ]
