# Generated by Django 3.0.5 on 2023-07-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0018_auto_20230715_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Uasin Gishu', 'Uasin Gishu'), ('Nandi', 'Nandi'), ('Meru', 'Meru'), ('Turkana', 'Turkana'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Isiolo', 'Homa Bay'), ('Samburu', 'Samburu'), ('Bomet', 'Bomet'), ('Kisii', 'Kisii'), ('Tana River', 'Tana River'), ('Lamu', 'Lamu'), ("Murang'a", 'Murang'), ('Homa Bay', 'Homa Bay'), ('Taita-Taveta', 'Taita-Taveta'), ('Nakuru', 'Nakuru'), ('Bungoma', 'Bungoma'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kilifi', 'Kilifi'), ('Kiambu', 'Kiambu'), ('Wajir', 'Wajir'), ('Nyamira', 'Nyamira'), ('Migori', 'Migori'), ('Kitui', 'Kitui'), ('Laikipia', 'Laikipia'), ('Makueni', 'Makueni'), ('Kirinyaga', 'Kirinyaga'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Mombasa', 'Mombasa'), ('Nyeri', 'Nyeri'), ('Garissa', 'Garissa'), ('Machakos', 'Machakos'), ('Kajiado', 'Kajiado'), ('Busia', 'Busia'), ('Nyandarua', 'Nyandarua'), ('Trans Nzoia', 'Trans Nzoia'), ('Kisumu', 'Kisumu'), ('Siaya', 'Siaya'), ('Nairobi', 'Nairobi'), ('Baringo', 'Baringo'), ('Kericho', 'Kericho'), ('West Pokot', 'West Pokot'), ('Embu', 'Embu'), ('Kakamega', 'Kakamega'), ('Vihiga', 'Vihiga'), ('Kwale', 'Kwale'), ('Narok', 'Narok')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='blood_drive',
            field=models.CharField(default='WPW', max_length=10),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Uasin Gishu', 'Uasin Gishu'), ('Nandi', 'Nandi'), ('Meru', 'Meru'), ('Turkana', 'Turkana'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Isiolo', 'Homa Bay'), ('Samburu', 'Samburu'), ('Bomet', 'Bomet'), ('Kisii', 'Kisii'), ('Tana River', 'Tana River'), ('Lamu', 'Lamu'), ("Murang'a", 'Murang'), ('Homa Bay', 'Homa Bay'), ('Taita-Taveta', 'Taita-Taveta'), ('Nakuru', 'Nakuru'), ('Bungoma', 'Bungoma'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kilifi', 'Kilifi'), ('Kiambu', 'Kiambu'), ('Wajir', 'Wajir'), ('Nyamira', 'Nyamira'), ('Migori', 'Migori'), ('Kitui', 'Kitui'), ('Laikipia', 'Laikipia'), ('Makueni', 'Makueni'), ('Kirinyaga', 'Kirinyaga'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Mombasa', 'Mombasa'), ('Nyeri', 'Nyeri'), ('Garissa', 'Garissa'), ('Machakos', 'Machakos'), ('Kajiado', 'Kajiado'), ('Busia', 'Busia'), ('Nyandarua', 'Nyandarua'), ('Trans Nzoia', 'Trans Nzoia'), ('Kisumu', 'Kisumu'), ('Siaya', 'Siaya'), ('Nairobi', 'Nairobi'), ('Baringo', 'Baringo'), ('Kericho', 'Kericho'), ('West Pokot', 'West Pokot'), ('Embu', 'Embu'), ('Kakamega', 'Kakamega'), ('Vihiga', 'Vihiga'), ('Kwale', 'Kwale'), ('Narok', 'Narok')], max_length=100),
        ),
    ]
