# Generated by Django 3.0.5 on 2023-07-15 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0016_auto_20230715_1841'),
        ('appointments', '0019_auto_20230715_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Kitui', 'Kitui'), ('Taita-Taveta', 'Taita-Taveta'), ('Kilifi', 'Kilifi'), ('Bungoma', 'Bungoma'), ('Kirinyaga', 'Kirinyaga'), ('Mandera', 'Mandera'), ('West Pokot', 'West Pokot'), ('Bomet', 'Bomet'), ('Lamu', 'Lamu'), ('Kisii', 'Kisii'), ('Kiambu', 'Kiambu'), ('Nandi', 'Nandi'), ('Migori', 'Migori'), ('Uasin Gishu', 'Uasin Gishu'), ('Turkana', 'Turkana'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Kericho', 'Kericho'), ('Kajiado', 'Kajiado'), ('Nairobi', 'Nairobi'), ('Nyamira', 'Nyamira'), ('Wajir', 'Wajir'), ('Nyeri', 'Nyeri'), ('Busia', 'Busia'), ('Embu', 'Embu'), ('Isiolo', 'Homa Bay'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Machakos', 'Machakos'), ('Trans Nzoia', 'Trans Nzoia'), ('Homa Bay', 'Homa Bay'), ('Kakamega', 'Kakamega'), ('Nakuru', 'Nakuru'), ('Meru', 'Meru'), ('Kwale', 'Kwale'), ('Marsabit', 'Marsabit'), ('Narok', 'Narok'), ('Kisumu', 'Kisumu'), ("Murang'a", 'Murang'), ('Baringo', 'Baringo'), ('Nyandarua', 'Nyandarua'), ('Garissa', 'Garissa'), ('Tana River', 'Tana River'), ('Laikipia', 'Laikipia'), ('Vihiga', 'Vihiga'), ('Mombasa', 'Mombasa'), ('Makueni', 'Makueni'), ('Siaya', 'Siaya'), ('Samburu', 'Samburu')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='blood_drive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blood.BloodDrives'),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Kitui', 'Kitui'), ('Taita-Taveta', 'Taita-Taveta'), ('Kilifi', 'Kilifi'), ('Bungoma', 'Bungoma'), ('Kirinyaga', 'Kirinyaga'), ('Mandera', 'Mandera'), ('West Pokot', 'West Pokot'), ('Bomet', 'Bomet'), ('Lamu', 'Lamu'), ('Kisii', 'Kisii'), ('Kiambu', 'Kiambu'), ('Nandi', 'Nandi'), ('Migori', 'Migori'), ('Uasin Gishu', 'Uasin Gishu'), ('Turkana', 'Turkana'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Kericho', 'Kericho'), ('Kajiado', 'Kajiado'), ('Nairobi', 'Nairobi'), ('Nyamira', 'Nyamira'), ('Wajir', 'Wajir'), ('Nyeri', 'Nyeri'), ('Busia', 'Busia'), ('Embu', 'Embu'), ('Isiolo', 'Homa Bay'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Machakos', 'Machakos'), ('Trans Nzoia', 'Trans Nzoia'), ('Homa Bay', 'Homa Bay'), ('Kakamega', 'Kakamega'), ('Nakuru', 'Nakuru'), ('Meru', 'Meru'), ('Kwale', 'Kwale'), ('Marsabit', 'Marsabit'), ('Narok', 'Narok'), ('Kisumu', 'Kisumu'), ("Murang'a", 'Murang'), ('Baringo', 'Baringo'), ('Nyandarua', 'Nyandarua'), ('Garissa', 'Garissa'), ('Tana River', 'Tana River'), ('Laikipia', 'Laikipia'), ('Vihiga', 'Vihiga'), ('Mombasa', 'Mombasa'), ('Makueni', 'Makueni'), ('Siaya', 'Siaya'), ('Samburu', 'Samburu')], max_length=100),
        ),
    ]
