# Generated by Django 3.0.5 on 2023-07-15 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0020_auto_20230715_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerregistration',
            name='id',
        ),
        migrations.AddField(
            model_name='volunteerregistration',
            name='volunteer_id',
            field=models.CharField(default=uuid.UUID('b41a98db-f88b-418e-b3ef-dd2d12b0ab17'), max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Kirinyaga', 'Kirinyaga'), ('Wajir', 'Wajir'), ('Kakamega', 'Kakamega'), ('Kisii', 'Kisii'), ('Nyamira', 'Nyamira'), ('Tana River', 'Tana River'), ('Kisumu', 'Kisumu'), ('Homa Bay', 'Homa Bay'), ('Taita-Taveta', 'Taita-Taveta'), ('Siaya', 'Siaya'), ('Marsabit', 'Marsabit'), ('Busia', 'Busia'), ("Murang'a", 'Murang'), ('Nyeri', 'Nyeri'), ('Vihiga', 'Vihiga'), ('Nairobi', 'Nairobi'), ('Mandera', 'Mandera'), ('Migori', 'Migori'), ('Nandi', 'Nandi'), ('Kilifi', 'Kilifi'), ('Makueni', 'Makueni'), ('Kiambu', 'Kiambu'), ('Lamu', 'Lamu'), ('Bomet', 'Bomet'), ('Machakos', 'Machakos'), ('Uasin Gishu', 'Uasin Gishu'), ('Kajiado', 'Kajiado'), ('Bungoma', 'Bungoma'), ('Mombasa', 'Mombasa'), ('Trans Nzoia', 'Trans Nzoia'), ('Kwale', 'Kwale'), ('Kericho', 'Kericho'), ('Garissa', 'Garissa'), ('Turkana', 'Turkana'), ('Kitui', 'Kitui'), ('Nyandarua', 'Nyandarua'), ('Baringo', 'Baringo'), ('Samburu', 'Samburu'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Meru', 'Meru'), ('Narok', 'Narok'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('West Pokot', 'West Pokot'), ('Laikipia', 'Laikipia'), ('Isiolo', 'Homa Bay'), ('Nakuru', 'Nakuru'), ('Embu', 'Embu')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Kirinyaga', 'Kirinyaga'), ('Wajir', 'Wajir'), ('Kakamega', 'Kakamega'), ('Kisii', 'Kisii'), ('Nyamira', 'Nyamira'), ('Tana River', 'Tana River'), ('Kisumu', 'Kisumu'), ('Homa Bay', 'Homa Bay'), ('Taita-Taveta', 'Taita-Taveta'), ('Siaya', 'Siaya'), ('Marsabit', 'Marsabit'), ('Busia', 'Busia'), ("Murang'a", 'Murang'), ('Nyeri', 'Nyeri'), ('Vihiga', 'Vihiga'), ('Nairobi', 'Nairobi'), ('Mandera', 'Mandera'), ('Migori', 'Migori'), ('Nandi', 'Nandi'), ('Kilifi', 'Kilifi'), ('Makueni', 'Makueni'), ('Kiambu', 'Kiambu'), ('Lamu', 'Lamu'), ('Bomet', 'Bomet'), ('Machakos', 'Machakos'), ('Uasin Gishu', 'Uasin Gishu'), ('Kajiado', 'Kajiado'), ('Bungoma', 'Bungoma'), ('Mombasa', 'Mombasa'), ('Trans Nzoia', 'Trans Nzoia'), ('Kwale', 'Kwale'), ('Kericho', 'Kericho'), ('Garissa', 'Garissa'), ('Turkana', 'Turkana'), ('Kitui', 'Kitui'), ('Nyandarua', 'Nyandarua'), ('Baringo', 'Baringo'), ('Samburu', 'Samburu'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Meru', 'Meru'), ('Narok', 'Narok'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('West Pokot', 'West Pokot'), ('Laikipia', 'Laikipia'), ('Isiolo', 'Homa Bay'), ('Nakuru', 'Nakuru'), ('Embu', 'Embu')], max_length=100),
        ),
    ]
