# Generated by Django 3.0.5 on 2023-07-15 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0022_auto_20230715_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerregistration',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Wajir', 'Wajir'), ('Kakamega', 'Kakamega'), ('Kwale', 'Kwale'), ('Narok', 'Narok'), ('Kajiado', 'Kajiado'), ('Kisumu', 'Kisumu'), ('Kiambu', 'Kiambu'), ('Embu', 'Embu'), ('Trans Nzoia', 'Trans Nzoia'), ('Nakuru', 'Nakuru'), ('Migori', 'Migori'), ('Kisii', 'Kisii'), ('Meru', 'Meru'), ('Isiolo', 'Homa Bay'), ('Nandi', 'Nandi'), ('Homa Bay', 'Homa Bay'), ('Makueni', 'Makueni'), ('Uasin Gishu', 'Uasin Gishu'), ('Kericho', 'Kericho'), ('Kilifi', 'Kilifi'), ('Laikipia', 'Laikipia'), ('Siaya', 'Siaya'), ('Nyamira', 'Nyamira'), ('Garissa', 'Garissa'), ('Bomet', 'Bomet'), ('Busia', 'Busia'), ('Mombasa', 'Mombasa'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Vihiga', 'Vihiga'), ('West Pokot', 'West Pokot'), ('Mandera', 'Mandera'), ('Nyeri', 'Nyeri'), ('Taita-Taveta', 'Taita-Taveta'), ('Bungoma', 'Bungoma'), ('Tana River', 'Tana River'), ('Marsabit', 'Marsabit'), ('Kitui', 'Kitui'), ('Kirinyaga', 'Kirinyaga'), ('Nairobi', 'Nairobi'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Samburu', 'Samburu'), ('Nyandarua', 'Nyandarua'), ('Turkana', 'Turkana'), ('Lamu', 'Lamu'), ('Baringo', 'Baringo'), ('Machakos', 'Machakos'), ("Murang'a", 'Murang')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Wajir', 'Wajir'), ('Kakamega', 'Kakamega'), ('Kwale', 'Kwale'), ('Narok', 'Narok'), ('Kajiado', 'Kajiado'), ('Kisumu', 'Kisumu'), ('Kiambu', 'Kiambu'), ('Embu', 'Embu'), ('Trans Nzoia', 'Trans Nzoia'), ('Nakuru', 'Nakuru'), ('Migori', 'Migori'), ('Kisii', 'Kisii'), ('Meru', 'Meru'), ('Isiolo', 'Homa Bay'), ('Nandi', 'Nandi'), ('Homa Bay', 'Homa Bay'), ('Makueni', 'Makueni'), ('Uasin Gishu', 'Uasin Gishu'), ('Kericho', 'Kericho'), ('Kilifi', 'Kilifi'), ('Laikipia', 'Laikipia'), ('Siaya', 'Siaya'), ('Nyamira', 'Nyamira'), ('Garissa', 'Garissa'), ('Bomet', 'Bomet'), ('Busia', 'Busia'), ('Mombasa', 'Mombasa'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Vihiga', 'Vihiga'), ('West Pokot', 'West Pokot'), ('Mandera', 'Mandera'), ('Nyeri', 'Nyeri'), ('Taita-Taveta', 'Taita-Taveta'), ('Bungoma', 'Bungoma'), ('Tana River', 'Tana River'), ('Marsabit', 'Marsabit'), ('Kitui', 'Kitui'), ('Kirinyaga', 'Kirinyaga'), ('Nairobi', 'Nairobi'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Samburu', 'Samburu'), ('Nyandarua', 'Nyandarua'), ('Turkana', 'Turkana'), ('Lamu', 'Lamu'), ('Baringo', 'Baringo'), ('Machakos', 'Machakos'), ("Murang'a", 'Murang')], max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='volunteer_id',
            field=models.CharField(default=uuid.UUID('89070b50-ed89-48f4-adf5-76d622750731'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
