# Generated by Django 3.0.5 on 2023-07-15 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0023_auto_20230715_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Bomet', 'Bomet'), ('Trans Nzoia', 'Trans Nzoia'), ('Baringo', 'Baringo'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Taita-Taveta', 'Taita-Taveta'), ("Murang'a", 'Murang'), ('Isiolo', 'Homa Bay'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Nandi', 'Nandi'), ('Meru', 'Meru'), ('Kitui', 'Kitui'), ('West Pokot', 'West Pokot'), ('Nairobi', 'Nairobi'), ('Kisumu', 'Kisumu'), ('Wajir', 'Wajir'), ('Vihiga', 'Vihiga'), ('Kakamega', 'Kakamega'), ('Nakuru', 'Nakuru'), ('Homa Bay', 'Homa Bay'), ('Bungoma', 'Bungoma'), ('Siaya', 'Siaya'), ('Kericho', 'Kericho'), ('Garissa', 'Garissa'), ('Makueni', 'Makueni'), ('Nyandarua', 'Nyandarua'), ('Kwale', 'Kwale'), ('Samburu', 'Samburu'), ('Laikipia', 'Laikipia'), ('Nyeri', 'Nyeri'), ('Kiambu', 'Kiambu'), ('Mandera', 'Mandera'), ('Kirinyaga', 'Kirinyaga'), ('Kisii', 'Kisii'), ('Tana River', 'Tana River'), ('Machakos', 'Machakos'), ('Lamu', 'Lamu'), ('Mombasa', 'Mombasa'), ('Migori', 'Migori'), ('Nyamira', 'Nyamira'), ('Marsabit', 'Marsabit'), ('Turkana', 'Turkana'), ('Busia', 'Busia'), ('Kilifi', 'Kilifi'), ('Uasin Gishu', 'Uasin Gishu'), ('Kajiado', 'Kajiado'), ('Narok', 'Narok'), ('Embu', 'Embu')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Bomet', 'Bomet'), ('Trans Nzoia', 'Trans Nzoia'), ('Baringo', 'Baringo'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Taita-Taveta', 'Taita-Taveta'), ("Murang'a", 'Murang'), ('Isiolo', 'Homa Bay'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Nandi', 'Nandi'), ('Meru', 'Meru'), ('Kitui', 'Kitui'), ('West Pokot', 'West Pokot'), ('Nairobi', 'Nairobi'), ('Kisumu', 'Kisumu'), ('Wajir', 'Wajir'), ('Vihiga', 'Vihiga'), ('Kakamega', 'Kakamega'), ('Nakuru', 'Nakuru'), ('Homa Bay', 'Homa Bay'), ('Bungoma', 'Bungoma'), ('Siaya', 'Siaya'), ('Kericho', 'Kericho'), ('Garissa', 'Garissa'), ('Makueni', 'Makueni'), ('Nyandarua', 'Nyandarua'), ('Kwale', 'Kwale'), ('Samburu', 'Samburu'), ('Laikipia', 'Laikipia'), ('Nyeri', 'Nyeri'), ('Kiambu', 'Kiambu'), ('Mandera', 'Mandera'), ('Kirinyaga', 'Kirinyaga'), ('Kisii', 'Kisii'), ('Tana River', 'Tana River'), ('Machakos', 'Machakos'), ('Lamu', 'Lamu'), ('Mombasa', 'Mombasa'), ('Migori', 'Migori'), ('Nyamira', 'Nyamira'), ('Marsabit', 'Marsabit'), ('Turkana', 'Turkana'), ('Busia', 'Busia'), ('Kilifi', 'Kilifi'), ('Uasin Gishu', 'Uasin Gishu'), ('Kajiado', 'Kajiado'), ('Narok', 'Narok'), ('Embu', 'Embu')], max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='volunteer_id',
            field=models.CharField(default=uuid.UUID('f960001f-54a2-409a-9f14-81fc79a9a7ba'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
