# Generated by Django 3.0.5 on 2023-07-15 22:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0024_auto_20230715_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='attendees',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Narok', 'Narok'), ('Marsabit', 'Marsabit'), ('Kitui', 'Kitui'), ('Kirinyaga', 'Kirinyaga'), ('Kiambu', 'Kiambu'), ('Nyamira', 'Nyamira'), ('Bungoma', 'Bungoma'), ('Kisumu', 'Kisumu'), ('Kisii', 'Kisii'), ('Homa Bay', 'Homa Bay'), ('Wajir', 'Wajir'), ('Nyandarua', 'Nyandarua'), ('Kwale', 'Kwale'), ('Kericho', 'Kericho'), ('Kajiado', 'Kajiado'), ('Laikipia', 'Laikipia'), ('Siaya', 'Siaya'), ('Garissa', 'Garissa'), ('Mombasa', 'Mombasa'), ('Turkana', 'Turkana'), ('Baringo', 'Baringo'), ('Makueni', 'Makueni'), ('Bomet', 'Bomet'), ('Nyeri', 'Nyeri'), ('Lamu', 'Lamu'), ('Meru', 'Meru'), ('Nairobi', 'Nairobi'), ('Machakos', 'Machakos'), ('Migori', 'Migori'), ('Kakamega', 'Kakamega'), ('Taita-Taveta', 'Taita-Taveta'), ('Nakuru', 'Nakuru'), ('Kilifi', 'Kilifi'), ('Vihiga', 'Vihiga'), ('Embu', 'Embu'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Busia', 'Busia'), ('Nandi', 'Nandi'), ("Murang'a", 'Murang'), ('Samburu', 'Samburu'), ('Tana River', 'Tana River'), ('Uasin Gishu', 'Uasin Gishu'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Trans Nzoia', 'Trans Nzoia'), ('West Pokot', 'West Pokot'), ('Isiolo', 'Homa Bay'), ('Mandera', 'Mandera')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Narok', 'Narok'), ('Marsabit', 'Marsabit'), ('Kitui', 'Kitui'), ('Kirinyaga', 'Kirinyaga'), ('Kiambu', 'Kiambu'), ('Nyamira', 'Nyamira'), ('Bungoma', 'Bungoma'), ('Kisumu', 'Kisumu'), ('Kisii', 'Kisii'), ('Homa Bay', 'Homa Bay'), ('Wajir', 'Wajir'), ('Nyandarua', 'Nyandarua'), ('Kwale', 'Kwale'), ('Kericho', 'Kericho'), ('Kajiado', 'Kajiado'), ('Laikipia', 'Laikipia'), ('Siaya', 'Siaya'), ('Garissa', 'Garissa'), ('Mombasa', 'Mombasa'), ('Turkana', 'Turkana'), ('Baringo', 'Baringo'), ('Makueni', 'Makueni'), ('Bomet', 'Bomet'), ('Nyeri', 'Nyeri'), ('Lamu', 'Lamu'), ('Meru', 'Meru'), ('Nairobi', 'Nairobi'), ('Machakos', 'Machakos'), ('Migori', 'Migori'), ('Kakamega', 'Kakamega'), ('Taita-Taveta', 'Taita-Taveta'), ('Nakuru', 'Nakuru'), ('Kilifi', 'Kilifi'), ('Vihiga', 'Vihiga'), ('Embu', 'Embu'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Busia', 'Busia'), ('Nandi', 'Nandi'), ("Murang'a", 'Murang'), ('Samburu', 'Samburu'), ('Tana River', 'Tana River'), ('Uasin Gishu', 'Uasin Gishu'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Trans Nzoia', 'Trans Nzoia'), ('West Pokot', 'West Pokot'), ('Isiolo', 'Homa Bay'), ('Mandera', 'Mandera')], max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='volunteer_id',
            field=models.CharField(default=uuid.UUID('a347a84c-aac9-449f-8e9c-4a4b52dab80d'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
