# Generated by Django 4.2.3 on 2023-07-17 06:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0026_auto_20230716_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Siaya', 'Siaya'), ('Vihiga', 'Vihiga'), ('Trans Nzoia', 'Trans Nzoia'), ('Makueni', 'Makueni'), ('Kwale', 'Kwale'), ('West Pokot', 'West Pokot'), ('Homa Bay', 'Homa Bay'), ('Kisii', 'Kisii'), ('Nyandarua', 'Nyandarua'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kitui', 'Kitui'), ("Murang'a", 'Murang'), ('Embu', 'Embu'), ('Kiambu', 'Kiambu'), ('Wajir', 'Wajir'), ('Busia', 'Busia'), ('Mombasa', 'Mombasa'), ('Garissa', 'Garissa'), ('Migori', 'Migori'), ('Kajiado', 'Kajiado'), ('Mandera', 'Mandera'), ('Nandi', 'Nandi'), ('Kirinyaga', 'Kirinyaga'), ('Nakuru', 'Nakuru'), ('Bomet', 'Bomet'), ('Bungoma', 'Bungoma'), ('Machakos', 'Machakos'), ('Nairobi', 'Nairobi'), ('Kericho', 'Kericho'), ('Turkana', 'Turkana'), ('Uasin Gishu', 'Uasin Gishu'), ('Tana River', 'Tana River'), ('Taita-Taveta', 'Taita-Taveta'), ('Lamu', 'Lamu'), ('Marsabit', 'Marsabit'), ('Kilifi', 'Kilifi'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Laikipia', 'Laikipia'), ('Isiolo', 'Homa Bay'), ('Meru', 'Meru'), ('Nyamira', 'Nyamira'), ('Baringo', 'Baringo'), ('Nyeri', 'Nyeri'), ('Samburu', 'Samburu'), ('Kisumu', 'Kisumu'), ('Kakamega', 'Kakamega'), ('Narok', 'Narok')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Siaya', 'Siaya'), ('Vihiga', 'Vihiga'), ('Trans Nzoia', 'Trans Nzoia'), ('Makueni', 'Makueni'), ('Kwale', 'Kwale'), ('West Pokot', 'West Pokot'), ('Homa Bay', 'Homa Bay'), ('Kisii', 'Kisii'), ('Nyandarua', 'Nyandarua'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kitui', 'Kitui'), ("Murang'a", 'Murang'), ('Embu', 'Embu'), ('Kiambu', 'Kiambu'), ('Wajir', 'Wajir'), ('Busia', 'Busia'), ('Mombasa', 'Mombasa'), ('Garissa', 'Garissa'), ('Migori', 'Migori'), ('Kajiado', 'Kajiado'), ('Mandera', 'Mandera'), ('Nandi', 'Nandi'), ('Kirinyaga', 'Kirinyaga'), ('Nakuru', 'Nakuru'), ('Bomet', 'Bomet'), ('Bungoma', 'Bungoma'), ('Machakos', 'Machakos'), ('Nairobi', 'Nairobi'), ('Kericho', 'Kericho'), ('Turkana', 'Turkana'), ('Uasin Gishu', 'Uasin Gishu'), ('Tana River', 'Tana River'), ('Taita-Taveta', 'Taita-Taveta'), ('Lamu', 'Lamu'), ('Marsabit', 'Marsabit'), ('Kilifi', 'Kilifi'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Laikipia', 'Laikipia'), ('Isiolo', 'Homa Bay'), ('Meru', 'Meru'), ('Nyamira', 'Nyamira'), ('Baringo', 'Baringo'), ('Nyeri', 'Nyeri'), ('Samburu', 'Samburu'), ('Kisumu', 'Kisumu'), ('Kakamega', 'Kakamega'), ('Narok', 'Narok')], max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='volunteer_id',
            field=models.CharField(default=uuid.UUID('cc1a61bf-fb2e-4205-8071-45c4e9065e07'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
