# Generated by Django 4.2.3 on 2023-07-17 08:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0027_alter_hostedblooddrives_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Mombasa', 'Mombasa'), ('Kirinyaga', 'Kirinyaga'), ('Bomet', 'Bomet'), ('Kisii', 'Kisii'), ('Lamu', 'Lamu'), ('Nairobi', 'Nairobi'), ('West Pokot', 'West Pokot'), ('Laikipia', 'Laikipia'), ('Meru', 'Meru'), ('Homa Bay', 'Homa Bay'), ('Kakamega', 'Kakamega'), ('Kitui', 'Kitui'), ('Garissa', 'Garissa'), ('Narok', 'Narok'), ('Mandera', 'Mandera'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Busia', 'Busia'), ('Kisumu', 'Kisumu'), ('Machakos', 'Machakos'), ('Samburu', 'Samburu'), ('Nandi', 'Nandi'), ('Kiambu', 'Kiambu'), ('Tana River', 'Tana River'), ("Murang'a", 'Murang'), ('Vihiga', 'Vihiga'), ('Bungoma', 'Bungoma'), ('Uasin Gishu', 'Uasin Gishu'), ('Kwale', 'Kwale'), ('Taita-Taveta', 'Taita-Taveta'), ('Nyandarua', 'Nyandarua'), ('Kericho', 'Kericho'), ('Marsabit', 'Marsabit'), ('Nakuru', 'Nakuru'), ('Baringo', 'Baringo'), ('Siaya', 'Siaya'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kajiado', 'Kajiado'), ('Migori', 'Migori'), ('Kilifi', 'Kilifi'), ('Nyeri', 'Nyeri'), ('Trans Nzoia', 'Trans Nzoia'), ('Nyamira', 'Nyamira'), ('Isiolo', 'Homa Bay'), ('Embu', 'Embu'), ('Wajir', 'Wajir'), ('Makueni', 'Makueni'), ('Turkana', 'Turkana')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Mombasa', 'Mombasa'), ('Kirinyaga', 'Kirinyaga'), ('Bomet', 'Bomet'), ('Kisii', 'Kisii'), ('Lamu', 'Lamu'), ('Nairobi', 'Nairobi'), ('West Pokot', 'West Pokot'), ('Laikipia', 'Laikipia'), ('Meru', 'Meru'), ('Homa Bay', 'Homa Bay'), ('Kakamega', 'Kakamega'), ('Kitui', 'Kitui'), ('Garissa', 'Garissa'), ('Narok', 'Narok'), ('Mandera', 'Mandera'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Busia', 'Busia'), ('Kisumu', 'Kisumu'), ('Machakos', 'Machakos'), ('Samburu', 'Samburu'), ('Nandi', 'Nandi'), ('Kiambu', 'Kiambu'), ('Tana River', 'Tana River'), ("Murang'a", 'Murang'), ('Vihiga', 'Vihiga'), ('Bungoma', 'Bungoma'), ('Uasin Gishu', 'Uasin Gishu'), ('Kwale', 'Kwale'), ('Taita-Taveta', 'Taita-Taveta'), ('Nyandarua', 'Nyandarua'), ('Kericho', 'Kericho'), ('Marsabit', 'Marsabit'), ('Nakuru', 'Nakuru'), ('Baringo', 'Baringo'), ('Siaya', 'Siaya'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kajiado', 'Kajiado'), ('Migori', 'Migori'), ('Kilifi', 'Kilifi'), ('Nyeri', 'Nyeri'), ('Trans Nzoia', 'Trans Nzoia'), ('Nyamira', 'Nyamira'), ('Isiolo', 'Homa Bay'), ('Embu', 'Embu'), ('Wajir', 'Wajir'), ('Makueni', 'Makueni'), ('Turkana', 'Turkana')], max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='volunteer_id',
            field=models.CharField(default=uuid.UUID('c2378183-936b-4422-af64-10ab913c005f'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
