# Generated by Django 4.2.3 on 2023-07-17 17:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0032_alter_hostedblooddrives_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Taita-Taveta', 'Taita-Taveta'), ('Busia', 'Busia'), ('Mombasa', 'Mombasa'), ('Kiambu', 'Kiambu'), ('Meru', 'Meru'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Lamu', 'Lamu'), ('Kajiado', 'Kajiado'), ('Nairobi', 'Nairobi'), ('Nandi', 'Nandi'), ("Murang'a", 'Murang'), ('Samburu', 'Samburu'), ('Tana River', 'Tana River'), ('Wajir', 'Wajir'), ('Turkana', 'Turkana'), ('Migori', 'Migori'), ('Kisumu', 'Kisumu'), ('Vihiga', 'Vihiga'), ('Garissa', 'Garissa'), ('Nyamira', 'Nyamira'), ('Siaya', 'Siaya'), ('Machakos', 'Machakos'), ('Kitui', 'Kitui'), ('Nyeri', 'Nyeri'), ('Trans Nzoia', 'Trans Nzoia'), ('Mandera', 'Mandera'), ('Isiolo', 'Homa Bay'), ('Makueni', 'Makueni'), ('Kwale', 'Kwale'), ('Uasin Gishu', 'Uasin Gishu'), ('Kericho', 'Kericho'), ('Embu', 'Embu'), ('Bungoma', 'Bungoma'), ('Bomet', 'Bomet'), ('Narok', 'Narok'), ('Kirinyaga', 'Kirinyaga'), ('Nyandarua', 'Nyandarua'), ('Nakuru', 'Nakuru'), ('Kakamega', 'Kakamega'), ('Laikipia', 'Laikipia'), ('Homa Bay', 'Homa Bay'), ('Kisii', 'Kisii'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Kilifi', 'Kilifi'), ('West Pokot', 'West Pokot'), ('Baringo', 'Baringo'), ('Marsabit', 'Marsabit')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Taita-Taveta', 'Taita-Taveta'), ('Busia', 'Busia'), ('Mombasa', 'Mombasa'), ('Kiambu', 'Kiambu'), ('Meru', 'Meru'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Lamu', 'Lamu'), ('Kajiado', 'Kajiado'), ('Nairobi', 'Nairobi'), ('Nandi', 'Nandi'), ("Murang'a", 'Murang'), ('Samburu', 'Samburu'), ('Tana River', 'Tana River'), ('Wajir', 'Wajir'), ('Turkana', 'Turkana'), ('Migori', 'Migori'), ('Kisumu', 'Kisumu'), ('Vihiga', 'Vihiga'), ('Garissa', 'Garissa'), ('Nyamira', 'Nyamira'), ('Siaya', 'Siaya'), ('Machakos', 'Machakos'), ('Kitui', 'Kitui'), ('Nyeri', 'Nyeri'), ('Trans Nzoia', 'Trans Nzoia'), ('Mandera', 'Mandera'), ('Isiolo', 'Homa Bay'), ('Makueni', 'Makueni'), ('Kwale', 'Kwale'), ('Uasin Gishu', 'Uasin Gishu'), ('Kericho', 'Kericho'), ('Embu', 'Embu'), ('Bungoma', 'Bungoma'), ('Bomet', 'Bomet'), ('Narok', 'Narok'), ('Kirinyaga', 'Kirinyaga'), ('Nyandarua', 'Nyandarua'), ('Nakuru', 'Nakuru'), ('Kakamega', 'Kakamega'), ('Laikipia', 'Laikipia'), ('Homa Bay', 'Homa Bay'), ('Kisii', 'Kisii'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Kilifi', 'Kilifi'), ('West Pokot', 'West Pokot'), ('Baringo', 'Baringo'), ('Marsabit', 'Marsabit')], max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='volunteer_id',
            field=models.CharField(default=uuid.UUID('cdfa41d6-1b1a-4b83-a39e-bf9dc8003ab8'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
