# Generated by Django 4.2.3 on 2023-07-20 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0038_alter_hostedblooddrives_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Kisii', 'Kisii'), ('Wajir', 'Wajir'), ('Bungoma', 'Bungoma'), ('Bomet', 'Bomet'), ('Makueni', 'Makueni'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Busia', 'Busia'), ('Embu', 'Embu'), ('Machakos', 'Machakos'), ('Lamu', 'Lamu'), ('Taita-Taveta', 'Taita-Taveta'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Laikipia', 'Laikipia'), ('Migori', 'Migori'), ('Nandi', 'Nandi'), ('Kisumu', 'Kisumu'), ('Nairobi', 'Nairobi'), ('Nyamira', 'Nyamira'), ('Turkana', 'Turkana'), ('Nyeri', 'Nyeri'), ('Uasin Gishu', 'Uasin Gishu'), ('Siaya', 'Siaya'), ("Murang'a", 'Murang'), ('Kilifi', 'Kilifi'), ('Kericho', 'Kericho'), ('Trans Nzoia', 'Trans Nzoia'), ('Kakamega', 'Kakamega'), ('Garissa', 'Garissa'), ('Tana River', 'Tana River'), ('Meru', 'Meru'), ('Nakuru', 'Nakuru'), ('Kiambu', 'Kiambu'), ('West Pokot', 'West Pokot'), ('Isiolo', 'Homa Bay'), ('Mombasa', 'Mombasa'), ('Kitui', 'Kitui'), ('Samburu', 'Samburu'), ('Kirinyaga', 'Kirinyaga'), ('Kwale', 'Kwale'), ('Nyandarua', 'Nyandarua'), ('Homa Bay', 'Homa Bay'), ('Narok', 'Narok'), ('Baringo', 'Baringo'), ('Vihiga', 'Vihiga'), ('Kajiado', 'Kajiado'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Kisii', 'Kisii'), ('Wajir', 'Wajir'), ('Bungoma', 'Bungoma'), ('Bomet', 'Bomet'), ('Makueni', 'Makueni'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Busia', 'Busia'), ('Embu', 'Embu'), ('Machakos', 'Machakos'), ('Lamu', 'Lamu'), ('Taita-Taveta', 'Taita-Taveta'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Laikipia', 'Laikipia'), ('Migori', 'Migori'), ('Nandi', 'Nandi'), ('Kisumu', 'Kisumu'), ('Nairobi', 'Nairobi'), ('Nyamira', 'Nyamira'), ('Turkana', 'Turkana'), ('Nyeri', 'Nyeri'), ('Uasin Gishu', 'Uasin Gishu'), ('Siaya', 'Siaya'), ("Murang'a", 'Murang'), ('Kilifi', 'Kilifi'), ('Kericho', 'Kericho'), ('Trans Nzoia', 'Trans Nzoia'), ('Kakamega', 'Kakamega'), ('Garissa', 'Garissa'), ('Tana River', 'Tana River'), ('Meru', 'Meru'), ('Nakuru', 'Nakuru'), ('Kiambu', 'Kiambu'), ('West Pokot', 'West Pokot'), ('Isiolo', 'Homa Bay'), ('Mombasa', 'Mombasa'), ('Kitui', 'Kitui'), ('Samburu', 'Samburu'), ('Kirinyaga', 'Kirinyaga'), ('Kwale', 'Kwale'), ('Nyandarua', 'Nyandarua'), ('Homa Bay', 'Homa Bay'), ('Narok', 'Narok'), ('Baringo', 'Baringo'), ('Vihiga', 'Vihiga'), ('Kajiado', 'Kajiado'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit')], max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='volunteer_id',
            field=models.CharField(default=uuid.UUID('9241fc63-cea5-45c8-88d5-316dfca2f839'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
