# Generated by Django 4.2.3 on 2023-07-24 04:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0040_alter_hostedblooddrives_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Uasin Gishu', 'Uasin Gishu'), ('Kisumu', 'Kisumu'), ('Samburu', 'Samburu'), ('Bomet', 'Bomet'), ('Taita-Taveta', 'Taita-Taveta'), ('Kakamega', 'Kakamega'), ('Embu', 'Embu'), ('Marsabit', 'Marsabit'), ('Kisii', 'Kisii'), ('Turkana', 'Turkana'), ('Makueni', 'Makueni'), ('Isiolo', 'Homa Bay'), ('Machakos', 'Machakos'), ('Migori', 'Migori'), ('Laikipia', 'Laikipia'), ('Busia', 'Busia'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Siaya', 'Siaya'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Narok', 'Narok'), ('Garissa', 'Garissa'), ('Nandi', 'Nandi'), ('Nakuru', 'Nakuru'), ('Wajir', 'Wajir'), ('Kitui', 'Kitui'), ('Kwale', 'Kwale'), ('Bungoma', 'Bungoma'), ('Kajiado', 'Kajiado'), ('Baringo', 'Baringo'), ('Kiambu', 'Kiambu'), ('Vihiga', 'Vihiga'), ('Nyandarua', 'Nyandarua'), ('Kirinyaga', 'Kirinyaga'), ('Homa Bay', 'Homa Bay'), ('Nyamira', 'Nyamira'), ("Murang'a", 'Murang'), ('Nyeri', 'Nyeri'), ('Trans Nzoia', 'Trans Nzoia'), ('West Pokot', 'West Pokot'), ('Mandera', 'Mandera'), ('Kilifi', 'Kilifi'), ('Kericho', 'Kericho'), ('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Tana River', 'Tana River'), ('Meru', 'Meru'), ('Lamu', 'Lamu')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Uasin Gishu', 'Uasin Gishu'), ('Kisumu', 'Kisumu'), ('Samburu', 'Samburu'), ('Bomet', 'Bomet'), ('Taita-Taveta', 'Taita-Taveta'), ('Kakamega', 'Kakamega'), ('Embu', 'Embu'), ('Marsabit', 'Marsabit'), ('Kisii', 'Kisii'), ('Turkana', 'Turkana'), ('Makueni', 'Makueni'), ('Isiolo', 'Homa Bay'), ('Machakos', 'Machakos'), ('Migori', 'Migori'), ('Laikipia', 'Laikipia'), ('Busia', 'Busia'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Siaya', 'Siaya'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Narok', 'Narok'), ('Garissa', 'Garissa'), ('Nandi', 'Nandi'), ('Nakuru', 'Nakuru'), ('Wajir', 'Wajir'), ('Kitui', 'Kitui'), ('Kwale', 'Kwale'), ('Bungoma', 'Bungoma'), ('Kajiado', 'Kajiado'), ('Baringo', 'Baringo'), ('Kiambu', 'Kiambu'), ('Vihiga', 'Vihiga'), ('Nyandarua', 'Nyandarua'), ('Kirinyaga', 'Kirinyaga'), ('Homa Bay', 'Homa Bay'), ('Nyamira', 'Nyamira'), ("Murang'a", 'Murang'), ('Nyeri', 'Nyeri'), ('Trans Nzoia', 'Trans Nzoia'), ('West Pokot', 'West Pokot'), ('Mandera', 'Mandera'), ('Kilifi', 'Kilifi'), ('Kericho', 'Kericho'), ('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Tana River', 'Tana River'), ('Meru', 'Meru'), ('Lamu', 'Lamu')], max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='volunteer_id',
            field=models.CharField(default=uuid.UUID('bc9080f7-1d4f-4b8a-b763-e26f99c71e74'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
