# Generated by Django 4.2.3 on 2023-07-24 10:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0042_alter_hostedblooddrives_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Mombasa', 'Mombasa'), ('Samburu', 'Samburu'), ('Laikipia', 'Laikipia'), ('Uasin Gishu', 'Uasin Gishu'), ('Siaya', 'Siaya'), ('Lamu', 'Lamu'), ('Vihiga', 'Vihiga'), ('Tana River', 'Tana River'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Kwale', 'Kwale'), ('Mandera', 'Mandera'), ('Kitui', 'Kitui'), ('Makueni', 'Makueni'), ('Kisii', 'Kisii'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Baringo', 'Baringo'), ('Narok', 'Narok'), ('Embu', 'Embu'), ('Kilifi', 'Kilifi'), ('Nyandarua', 'Nyandarua'), ('Kisumu', 'Kisumu'), ('Meru', 'Meru'), ('Nandi', 'Nandi'), ('Taita-Taveta', 'Taita-Taveta'), ('Bungoma', 'Bungoma'), ('Kirinyaga', 'Kirinyaga'), ('Bomet', 'Bomet'), ('Machakos', 'Machakos'), ('Kiambu', 'Kiambu'), ('Homa Bay', 'Homa Bay'), ('Garissa', 'Garissa'), ('Isiolo', 'Homa Bay'), ('Kakamega', 'Kakamega'), ('Busia', 'Busia'), ('Kericho', 'Kericho'), ('Kajiado', 'Kajiado'), ('Trans Nzoia', 'Trans Nzoia'), ('Migori', 'Migori'), ('Nairobi', 'Nairobi'), ('Marsabit', 'Marsabit'), ("Murang'a", 'Murang'), ('Turkana', 'Turkana'), ('Wajir', 'Wajir'), ('West Pokot', 'West Pokot'), ('Nyamira', 'Nyamira'), ('Nakuru', 'Nakuru'), ('Nyeri', 'Nyeri')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Mombasa', 'Mombasa'), ('Samburu', 'Samburu'), ('Laikipia', 'Laikipia'), ('Uasin Gishu', 'Uasin Gishu'), ('Siaya', 'Siaya'), ('Lamu', 'Lamu'), ('Vihiga', 'Vihiga'), ('Tana River', 'Tana River'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Kwale', 'Kwale'), ('Mandera', 'Mandera'), ('Kitui', 'Kitui'), ('Makueni', 'Makueni'), ('Kisii', 'Kisii'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Baringo', 'Baringo'), ('Narok', 'Narok'), ('Embu', 'Embu'), ('Kilifi', 'Kilifi'), ('Nyandarua', 'Nyandarua'), ('Kisumu', 'Kisumu'), ('Meru', 'Meru'), ('Nandi', 'Nandi'), ('Taita-Taveta', 'Taita-Taveta'), ('Bungoma', 'Bungoma'), ('Kirinyaga', 'Kirinyaga'), ('Bomet', 'Bomet'), ('Machakos', 'Machakos'), ('Kiambu', 'Kiambu'), ('Homa Bay', 'Homa Bay'), ('Garissa', 'Garissa'), ('Isiolo', 'Homa Bay'), ('Kakamega', 'Kakamega'), ('Busia', 'Busia'), ('Kericho', 'Kericho'), ('Kajiado', 'Kajiado'), ('Trans Nzoia', 'Trans Nzoia'), ('Migori', 'Migori'), ('Nairobi', 'Nairobi'), ('Marsabit', 'Marsabit'), ("Murang'a", 'Murang'), ('Turkana', 'Turkana'), ('Wajir', 'Wajir'), ('West Pokot', 'West Pokot'), ('Nyamira', 'Nyamira'), ('Nakuru', 'Nakuru'), ('Nyeri', 'Nyeri')], max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='volunteer_id',
            field=models.CharField(default=uuid.UUID('9024a8a8-02b9-488b-8423-76ae69d73aa6'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
