# Generated by Django 4.2.3 on 2023-07-24 11:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0044_alter_hostedblooddrives_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Tana River', 'Tana River'), ('Kisii', 'Kisii'), ('Kitui', 'Kitui'), ('Uasin Gishu', 'Uasin Gishu'), ('Kisumu', 'Kisumu'), ('Kericho', 'Kericho'), ('Nandi', 'Nandi'), ('Kajiado', 'Kajiado'), ('Kilifi', 'Kilifi'), ('Marsabit', 'Marsabit'), ('Nyeri', 'Nyeri'), ('Siaya', 'Siaya'), ('Turkana', 'Turkana'), ('Kwale', 'Kwale'), ('Samburu', 'Samburu'), ("Murang'a", 'Murang'), ('Migori', 'Migori'), ('Kakamega', 'Kakamega'), ('Nyandarua', 'Nyandarua'), ('Baringo', 'Baringo'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Makueni', 'Makueni'), ('Busia', 'Busia'), ('Bungoma', 'Bungoma'), ('Lamu', 'Lamu'), ('Nakuru', 'Nakuru'), ('Mandera', 'Mandera'), ('Laikipia', 'Laikipia'), ('Kirinyaga', 'Kirinyaga'), ('West Pokot', 'West Pokot'), ('Trans Nzoia', 'Trans Nzoia'), ('Meru', 'Meru'), ('Isiolo', 'Homa Bay'), ('Wajir', 'Wajir'), ('Homa Bay', 'Homa Bay'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Embu', 'Embu'), ('Taita-Taveta', 'Taita-Taveta'), ('Mombasa', 'Mombasa'), ('Narok', 'Narok'), ('Vihiga', 'Vihiga'), ('Nairobi', 'Nairobi'), ('Machakos', 'Machakos'), ('Kiambu', 'Kiambu'), ('Bomet', 'Bomet'), ('Garissa', 'Garissa'), ('Nyamira', 'Nyamira')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Tana River', 'Tana River'), ('Kisii', 'Kisii'), ('Kitui', 'Kitui'), ('Uasin Gishu', 'Uasin Gishu'), ('Kisumu', 'Kisumu'), ('Kericho', 'Kericho'), ('Nandi', 'Nandi'), ('Kajiado', 'Kajiado'), ('Kilifi', 'Kilifi'), ('Marsabit', 'Marsabit'), ('Nyeri', 'Nyeri'), ('Siaya', 'Siaya'), ('Turkana', 'Turkana'), ('Kwale', 'Kwale'), ('Samburu', 'Samburu'), ("Murang'a", 'Murang'), ('Migori', 'Migori'), ('Kakamega', 'Kakamega'), ('Nyandarua', 'Nyandarua'), ('Baringo', 'Baringo'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Makueni', 'Makueni'), ('Busia', 'Busia'), ('Bungoma', 'Bungoma'), ('Lamu', 'Lamu'), ('Nakuru', 'Nakuru'), ('Mandera', 'Mandera'), ('Laikipia', 'Laikipia'), ('Kirinyaga', 'Kirinyaga'), ('West Pokot', 'West Pokot'), ('Trans Nzoia', 'Trans Nzoia'), ('Meru', 'Meru'), ('Isiolo', 'Homa Bay'), ('Wajir', 'Wajir'), ('Homa Bay', 'Homa Bay'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Embu', 'Embu'), ('Taita-Taveta', 'Taita-Taveta'), ('Mombasa', 'Mombasa'), ('Narok', 'Narok'), ('Vihiga', 'Vihiga'), ('Nairobi', 'Nairobi'), ('Machakos', 'Machakos'), ('Kiambu', 'Kiambu'), ('Bomet', 'Bomet'), ('Garissa', 'Garissa'), ('Nyamira', 'Nyamira')], max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='volunteer_id',
            field=models.CharField(default=uuid.UUID('c2e82448-d7d9-448d-8dda-8b0542f58d6b'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
