# Generated by Django 4.2.3 on 2023-08-19 18:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0045_alter_hostedblooddrives_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Bungoma', 'Bungoma'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kitui', 'Kitui'), ('Kiambu', 'Kiambu'), ('Laikipia', 'Laikipia'), ('Kericho', 'Kericho'), ('Kajiado', 'Kajiado'), ('Mandera', 'Mandera'), ('Embu', 'Embu'), ('Nyamira', 'Nyamira'), ('Nyeri', 'Nyeri'), ('Trans Nzoia', 'Trans Nzoia'), ('Meru', 'Meru'), ('Kisii', 'Kisii'), ('Samburu', 'Samburu'), ('Nandi', 'Nandi'), ('Kwale', 'Kwale'), ('Garissa', 'Garissa'), ('Migori', 'Migori'), ('Nairobi', 'Nairobi'), ('Tana River', 'Tana River'), ('West Pokot', 'West Pokot'), ('Lamu', 'Lamu'), ('Busia', 'Busia'), ('Siaya', 'Siaya'), ('Kirinyaga', 'Kirinyaga'), ('Uasin Gishu', 'Uasin Gishu'), ('Nyandarua', 'Nyandarua'), ('Kakamega', 'Kakamega'), ('Kilifi', 'Kilifi'), ('Machakos', 'Machakos'), ('Isiolo', 'Homa Bay'), ('Wajir', 'Wajir'), ('Taita-Taveta', 'Taita-Taveta'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ("Murang'a", 'Murang'), ('Homa Bay', 'Homa Bay'), ('Baringo', 'Baringo'), ('Makueni', 'Makueni'), ('Vihiga', 'Vihiga'), ('Marsabit', 'Marsabit'), ('Narok', 'Narok'), ('Bomet', 'Bomet'), ('Nakuru', 'Nakuru'), ('Turkana', 'Turkana')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Bungoma', 'Bungoma'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kitui', 'Kitui'), ('Kiambu', 'Kiambu'), ('Laikipia', 'Laikipia'), ('Kericho', 'Kericho'), ('Kajiado', 'Kajiado'), ('Mandera', 'Mandera'), ('Embu', 'Embu'), ('Nyamira', 'Nyamira'), ('Nyeri', 'Nyeri'), ('Trans Nzoia', 'Trans Nzoia'), ('Meru', 'Meru'), ('Kisii', 'Kisii'), ('Samburu', 'Samburu'), ('Nandi', 'Nandi'), ('Kwale', 'Kwale'), ('Garissa', 'Garissa'), ('Migori', 'Migori'), ('Nairobi', 'Nairobi'), ('Tana River', 'Tana River'), ('West Pokot', 'West Pokot'), ('Lamu', 'Lamu'), ('Busia', 'Busia'), ('Siaya', 'Siaya'), ('Kirinyaga', 'Kirinyaga'), ('Uasin Gishu', 'Uasin Gishu'), ('Nyandarua', 'Nyandarua'), ('Kakamega', 'Kakamega'), ('Kilifi', 'Kilifi'), ('Machakos', 'Machakos'), ('Isiolo', 'Homa Bay'), ('Wajir', 'Wajir'), ('Taita-Taveta', 'Taita-Taveta'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ("Murang'a", 'Murang'), ('Homa Bay', 'Homa Bay'), ('Baringo', 'Baringo'), ('Makueni', 'Makueni'), ('Vihiga', 'Vihiga'), ('Marsabit', 'Marsabit'), ('Narok', 'Narok'), ('Bomet', 'Bomet'), ('Nakuru', 'Nakuru'), ('Turkana', 'Turkana')], max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='volunteer_id',
            field=models.CharField(default=uuid.UUID('fbd5df11-d684-4432-ac19-c6863a60b1a2'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
