# Generated by Django 4.2.3 on 2023-08-22 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0046_alter_hostedblooddrives_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Homa Bay', 'Homa Bay'), ('Wajir', 'Wajir'), ('Nyandarua', 'Nyandarua'), ('Turkana', 'Turkana'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Kilifi', 'Kilifi'), ('Kisii', 'Kisii'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Makueni', 'Makueni'), ('Tana River', 'Tana River'), ('Kirinyaga', 'Kirinyaga'), ('Migori', 'Migori'), ('Nyeri', 'Nyeri'), ('Busia', 'Busia'), ('Nakuru', 'Nakuru'), ('Mandera', 'Mandera'), ('Nairobi', 'Nairobi'), ('Siaya', 'Siaya'), ('Trans Nzoia', 'Trans Nzoia'), ('Isiolo', 'Homa Bay'), ('Marsabit', 'Marsabit'), ('Bomet', 'Bomet'), ("Murang'a", 'Murang'), ('Machakos', 'Machakos'), ('Kisumu', 'Kisumu'), ('Uasin Gishu', 'Uasin Gishu'), ('Vihiga', 'Vihiga'), ('Baringo', 'Baringo'), ('Meru', 'Meru'), ('Samburu', 'Samburu'), ('Nyamira', 'Nyamira'), ('Kiambu', 'Kiambu'), ('Nandi', 'Nandi'), ('West Pokot', 'West Pokot'), ('Taita-Taveta', 'Taita-Taveta'), ('Garissa', 'Garissa'), ('Kericho', 'Kericho'), ('Narok', 'Narok'), ('Kajiado', 'Kajiado'), ('Kakamega', 'Kakamega'), ('Lamu', 'Lamu'), ('Kitui', 'Kitui'), ('Kwale', 'Kwale'), ('Laikipia', 'Laikipia'), ('Embu', 'Embu'), ('Mombasa', 'Mombasa'), ('Bungoma', 'Bungoma')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Homa Bay', 'Homa Bay'), ('Wajir', 'Wajir'), ('Nyandarua', 'Nyandarua'), ('Turkana', 'Turkana'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Kilifi', 'Kilifi'), ('Kisii', 'Kisii'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Makueni', 'Makueni'), ('Tana River', 'Tana River'), ('Kirinyaga', 'Kirinyaga'), ('Migori', 'Migori'), ('Nyeri', 'Nyeri'), ('Busia', 'Busia'), ('Nakuru', 'Nakuru'), ('Mandera', 'Mandera'), ('Nairobi', 'Nairobi'), ('Siaya', 'Siaya'), ('Trans Nzoia', 'Trans Nzoia'), ('Isiolo', 'Homa Bay'), ('Marsabit', 'Marsabit'), ('Bomet', 'Bomet'), ("Murang'a", 'Murang'), ('Machakos', 'Machakos'), ('Kisumu', 'Kisumu'), ('Uasin Gishu', 'Uasin Gishu'), ('Vihiga', 'Vihiga'), ('Baringo', 'Baringo'), ('Meru', 'Meru'), ('Samburu', 'Samburu'), ('Nyamira', 'Nyamira'), ('Kiambu', 'Kiambu'), ('Nandi', 'Nandi'), ('West Pokot', 'West Pokot'), ('Taita-Taveta', 'Taita-Taveta'), ('Garissa', 'Garissa'), ('Kericho', 'Kericho'), ('Narok', 'Narok'), ('Kajiado', 'Kajiado'), ('Kakamega', 'Kakamega'), ('Lamu', 'Lamu'), ('Kitui', 'Kitui'), ('Kwale', 'Kwale'), ('Laikipia', 'Laikipia'), ('Embu', 'Embu'), ('Mombasa', 'Mombasa'), ('Bungoma', 'Bungoma')], max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='volunteer_id',
            field=models.CharField(default=uuid.UUID('5aa787a9-1c75-4a35-8276-d55e203f55d0'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
