# Generated by Django 4.2.3 on 2023-08-23 08:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0047_alter_hostedblooddrives_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedblooddrives',
            name='county',
            field=models.CharField(choices=[('Nakuru', 'Nakuru'), ('Kwale', 'Kwale'), ('Kakamega', 'Kakamega'), ('Lamu', 'Lamu'), ('Baringo', 'Baringo'), ('Nairobi', 'Nairobi'), ('Laikipia', 'Laikipia'), ('Garissa', 'Garissa'), ('Tana River', 'Tana River'), ('Meru', 'Meru'), ("Murang'a", 'Murang'), ('Embu', 'Embu'), ('Narok', 'Narok'), ('Nyamira', 'Nyamira'), ('Kisumu', 'Kisumu'), ('Bomet', 'Bomet'), ('Mandera', 'Mandera'), ('Taita-Taveta', 'Taita-Taveta'), ('Nyandarua', 'Nyandarua'), ('Nandi', 'Nandi'), ('Busia', 'Busia'), ('Machakos', 'Machakos'), ('Bungoma', 'Bungoma'), ('Isiolo', 'Homa Bay'), ('Vihiga', 'Vihiga'), ('Homa Bay', 'Homa Bay'), ('Samburu', 'Samburu'), ('Kericho', 'Kericho'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Kirinyaga', 'Kirinyaga'), ('Siaya', 'Siaya'), ('Marsabit', 'Marsabit'), ('Kisii', 'Kisii'), ('Uasin Gishu', 'Uasin Gishu'), ('West Pokot', 'West Pokot'), ('Kiambu', 'Kiambu'), ('Mombasa', 'Mombasa'), ('Wajir', 'Wajir'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Nyeri', 'Nyeri'), ('Kitui', 'Kitui'), ('Turkana', 'Turkana'), ('Trans Nzoia', 'Trans Nzoia'), ('Kajiado', 'Kajiado'), ('Kilifi', 'Kilifi'), ('Migori', 'Migori'), ('Makueni', 'Makueni')], max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='location',
            field=models.CharField(choices=[('Nakuru', 'Nakuru'), ('Kwale', 'Kwale'), ('Kakamega', 'Kakamega'), ('Lamu', 'Lamu'), ('Baringo', 'Baringo'), ('Nairobi', 'Nairobi'), ('Laikipia', 'Laikipia'), ('Garissa', 'Garissa'), ('Tana River', 'Tana River'), ('Meru', 'Meru'), ("Murang'a", 'Murang'), ('Embu', 'Embu'), ('Narok', 'Narok'), ('Nyamira', 'Nyamira'), ('Kisumu', 'Kisumu'), ('Bomet', 'Bomet'), ('Mandera', 'Mandera'), ('Taita-Taveta', 'Taita-Taveta'), ('Nyandarua', 'Nyandarua'), ('Nandi', 'Nandi'), ('Busia', 'Busia'), ('Machakos', 'Machakos'), ('Bungoma', 'Bungoma'), ('Isiolo', 'Homa Bay'), ('Vihiga', 'Vihiga'), ('Homa Bay', 'Homa Bay'), ('Samburu', 'Samburu'), ('Kericho', 'Kericho'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Kirinyaga', 'Kirinyaga'), ('Siaya', 'Siaya'), ('Marsabit', 'Marsabit'), ('Kisii', 'Kisii'), ('Uasin Gishu', 'Uasin Gishu'), ('West Pokot', 'West Pokot'), ('Kiambu', 'Kiambu'), ('Mombasa', 'Mombasa'), ('Wajir', 'Wajir'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Nyeri', 'Nyeri'), ('Kitui', 'Kitui'), ('Turkana', 'Turkana'), ('Trans Nzoia', 'Trans Nzoia'), ('Kajiado', 'Kajiado'), ('Kilifi', 'Kilifi'), ('Migori', 'Migori'), ('Makueni', 'Makueni')], max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='volunteer_id',
            field=models.CharField(default=uuid.UUID('ed9cd0e5-0560-4cf7-8606-265c45a8f956'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
