# Generated by Django 3.0.5 on 2023-07-12 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_bloodrequest_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCodes',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BloodDrives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=40)),
                ('county', models.CharField(choices=[('Marsabit', 'Marsabit'), ('Kisumu', 'Kisumu'), ('Nyeri', 'Nyeri'), ('Busia', 'Busia'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Trans Nzoia', 'Trans Nzoia'), ('Turkana', 'Turkana'), ('Taita-Taveta', 'Taita-Taveta'), ('Meru', 'Meru'), ('Vihiga', 'Vihiga'), ('Kwale', 'Kwale'), ('Makueni', 'Makueni'), ('Uasin Gishu', 'Uasin Gishu'), ('Mombasa', 'Mombasa'), ('Embu', 'Embu'), ('Nandi', 'Nandi'), ('Wajir', 'Wajir'), ('Nyandarua', 'Nyandarua'), ('Isiolo', 'Homa Bay'), ('Lamu', 'Lamu'), ('Nairobi', 'Nairobi'), ('Kitui', 'Kitui'), ('West Pokot', 'West Pokot'), ('Kericho', 'Kericho'), ('Kiambu', 'Kiambu'), ('Machakos', 'Machakos'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Nakuru', 'Nakuru'), ('Migori', 'Migori'), ('Mandera', 'Mandera'), ('Laikipia', 'Laikipia'), ('Narok', 'Narok'), ('Kakamega', 'Kakamega'), ('Bomet', 'Bomet'), ('Kilifi', 'Kilifi'), ('Kirinyaga', 'Kirinyaga'), ('Baringo', 'Baringo'), ('Tana River', 'Tana River'), ('Bungoma', 'Bungoma'), ('Kisii', 'Kisii'), ('Garissa', 'Garissa'), ("Murang'a", 'Murang'), ('Nyamira', 'Nyamira'), ('Siaya', 'Siaya'), ('Homa Bay', 'Homa Bay'), ('Samburu', 'Samburu'), ('Kajiado', 'Kajiado')], max_length=15)),
                ('date', models.DateField()),
                ('location_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.LocationCodes')),
            ],
        ),
    ]
