# Generated by Django 3.0.5 on 2023-07-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0012_auto_20230715_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddrives',
            name='volunteers',
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Siaya', 'Siaya'), ('Makueni', 'Makueni'), ('Kericho', 'Kericho'), ('Embu', 'Embu'), ('Mombasa', 'Mombasa'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Garissa', 'Garissa'), ('Mandera', 'Mandera'), ('Bungoma', 'Bungoma'), ('Wajir', 'Wajir'), ('Laikipia', 'Laikipia'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Marsabit', 'Marsabit'), ('Kisii', 'Kisii'), ('Kajiado', 'Kajiado'), ('Migori', 'Migori'), ('Kakamega', 'Kakamega'), ('Meru', 'Meru'), ('West Pokot', 'West Pokot'), ('Isiolo', 'Homa Bay'), ('Baringo', 'Baringo'), ('Machakos', 'Machakos'), ('Kiambu', 'Kiambu'), ('Vihiga', 'Vihiga'), ('Kisumu', 'Kisumu'), ('Turkana', 'Turkana'), ('Busia', 'Busia'), ('Nyeri', 'Nyeri'), ('Kilifi', 'Kilifi'), ('Uasin Gishu', 'Uasin Gishu'), ('Kwale', 'Kwale'), ('Kitui', 'Kitui'), ('Bomet', 'Bomet'), ('Samburu', 'Samburu'), ('Narok', 'Narok'), ('Kirinyaga', 'Kirinyaga'), ("Murang'a", 'Murang'), ('Lamu', 'Lamu'), ('Homa Bay', 'Homa Bay'), ('Tana River', 'Tana River'), ('Nairobi', 'Nairobi'), ('Trans Nzoia', 'Trans Nzoia'), ('Nakuru', 'Nakuru'), ('Nyandarua', 'Nyandarua'), ('Nyamira', 'Nyamira'), ('Nandi', 'Nandi'), ('Taita-Taveta', 'Taita-Taveta')], max_length=15),
        ),
    ]
