# Generated by Django 3.0.5 on 2023-07-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0013_auto_20230715_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default='Remove immediately', max_length=20),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Homa Bay', 'Homa Bay'), ('Kirinyaga', 'Kirinyaga'), ('Kitui', 'Kitui'), ('Migori', 'Migori'), ('Meru', 'Meru'), ('Nyeri', 'Nyeri'), ('Kiambu', 'Kiambu'), ('Samburu', 'Samburu'), ('Uasin Gishu', 'Uasin Gishu'), ('Tana River', 'Tana River'), ('Kakamega', 'Kakamega'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Bomet', 'Bomet'), ('Mombasa', 'Mombasa'), ('Kisii', 'Kisii'), ('Isiolo', 'Homa Bay'), ('Garissa', 'Garissa'), ('Trans Nzoia', 'Trans Nzoia'), ('Machakos', 'Machakos'), ('Wajir', 'Wajir'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kwale', 'Kwale'), ('Nakuru', 'Nakuru'), ('Marsabit', 'Marsabit'), ('Vihiga', 'Vihiga'), ('Nairobi', 'Nairobi'), ('Narok', 'Narok'), ('Lamu', 'Lamu'), ('Taita-Taveta', 'Taita-Taveta'), ('Embu', 'Embu'), ('Turkana', 'Turkana'), ('Kisumu', 'Kisumu'), ('Laikipia', 'Laikipia'), ('Baringo', 'Baringo'), ('Kilifi', 'Kilifi'), ('Nandi', 'Nandi'), ('Makueni', 'Makueni'), ('Mandera', 'Mandera'), ('Busia', 'Busia'), ('Nyamira', 'Nyamira'), ('Siaya', 'Siaya'), ('Kajiado', 'Kajiado'), ("Murang'a", 'Murang'), ('Bungoma', 'Bungoma'), ('West Pokot', 'West Pokot'), ('Kericho', 'Kericho'), ('Nyandarua', 'Nyandarua')], max_length=15),
        ),
    ]
