# Generated by Django 3.0.5 on 2023-07-15 15:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0015_auto_20230715_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Kitui', 'Kitui'), ('Taita-Taveta', 'Taita-Taveta'), ('Bungoma', 'Bungoma'), ('Kirinyaga', 'Kirinyaga'), ('Kilifi', 'Kilifi'), ('West Pokot', 'West Pokot'), ('Mandera', 'Mandera'), ('Bomet', 'Bomet'), ('Lamu', 'Lamu'), ('Kisii', 'Kisii'), ('Kiambu', 'Kiambu'), ('Nandi', 'Nandi'), ('Migori', 'Migori'), ('Uasin Gishu', 'Uasin Gishu'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Turkana', 'Turkana'), ('Kericho', 'Kericho'), ('Kajiado', 'Kajiado'), ('Nairobi', 'Nairobi'), ('Nyamira', 'Nyamira'), ('Wajir', 'Wajir'), ('Nyeri', 'Nyeri'), ('Busia', 'Busia'), ('Embu', 'Embu'), ('Isiolo', 'Homa Bay'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Machakos', 'Machakos'), ('Trans Nzoia', 'Trans Nzoia'), ('Homa Bay', 'Homa Bay'), ('Kakamega', 'Kakamega'), ('Nakuru', 'Nakuru'), ('Meru', 'Meru'), ('Narok', 'Narok'), ('Kwale', 'Kwale'), ('Marsabit', 'Marsabit'), ('Kisumu', 'Kisumu'), ("Murang'a", 'Murang'), ('Baringo', 'Baringo'), ('Nyandarua', 'Nyandarua'), ('Tana River', 'Tana River'), ('Garissa', 'Garissa'), ('Laikipia', 'Laikipia'), ('Vihiga', 'Vihiga'), ('Mombasa', 'Mombasa'), ('Makueni', 'Makueni'), ('Siaya', 'Siaya'), ('Samburu', 'Samburu')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default=uuid.UUID('37f95b7c-5fcb-4fb1-abd3-635776e1710b'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
