# Generated by Django 3.0.5 on 2023-07-15 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0016_auto_20230715_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Narok', 'Narok'), ('Taita-Taveta', 'Taita-Taveta'), ('West Pokot', 'West Pokot'), ('Kitui', 'Kitui'), ('Kakamega', 'Kakamega'), ('Kiambu', 'Kiambu'), ('Lamu', 'Lamu'), ('Migori', 'Migori'), ('Laikipia', 'Laikipia'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Wajir', 'Wajir'), ('Meru', 'Meru'), ('Samburu', 'Samburu'), ('Busia', 'Busia'), ('Kwale', 'Kwale'), ('Mombasa', 'Mombasa'), ('Bomet', 'Bomet'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Baringo', 'Baringo'), ('Trans Nzoia', 'Trans Nzoia'), ('Nyeri', 'Nyeri'), ('Kisii', 'Kisii'), ('Turkana', 'Turkana'), ('Garissa', 'Garissa'), ('Nyandarua', 'Nyandarua'), ("Murang'a", 'Murang'), ('Nyamira', 'Nyamira'), ('Kajiado', 'Kajiado'), ('Nandi', 'Nandi'), ('Kilifi', 'Kilifi'), ('Bungoma', 'Bungoma'), ('Isiolo', 'Homa Bay'), ('Makueni', 'Makueni'), ('Vihiga', 'Vihiga'), ('Nakuru', 'Nakuru'), ('Embu', 'Embu'), ('Machakos', 'Machakos'), ('Homa Bay', 'Homa Bay'), ('Tana River', 'Tana River'), ('Marsabit', 'Marsabit'), ('Kisumu', 'Kisumu'), ('Mandera', 'Mandera'), ('Kirinyaga', 'Kirinyaga'), ('Nairobi', 'Nairobi'), ('Kericho', 'Kericho'), ('Siaya', 'Siaya'), ('Uasin Gishu', 'Uasin Gishu')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default=uuid.UUID('7843db83-26c8-4a17-a2eb-92a2b6599cb5'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
