# Generated by Django 3.0.5 on 2023-07-15 16:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0017_auto_20230715_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Tana River', 'Tana River'), ('Nakuru', 'Nakuru'), ('Kajiado', 'Kajiado'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Nyeri', 'Nyeri'), ('Kilifi', 'Kilifi'), ('Kiambu', 'Kiambu'), ('Isiolo', 'Homa Bay'), ('Nyamira', 'Nyamira'), ('Bungoma', 'Bungoma'), ('Narok', 'Narok'), ('Nyandarua', 'Nyandarua'), ('Garissa', 'Garissa'), ("Murang'a", 'Murang'), ('Meru', 'Meru'), ('West Pokot', 'West Pokot'), ('Uasin Gishu', 'Uasin Gishu'), ('Wajir', 'Wajir'), ('Baringo', 'Baringo'), ('Laikipia', 'Laikipia'), ('Kirinyaga', 'Kirinyaga'), ('Bomet', 'Bomet'), ('Nairobi', 'Nairobi'), ('Vihiga', 'Vihiga'), ('Trans Nzoia', 'Trans Nzoia'), ('Busia', 'Busia'), ('Nandi', 'Nandi'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Kisumu', 'Kisumu'), ('Lamu', 'Lamu'), ('Turkana', 'Turkana'), ('Kitui', 'Kitui'), ('Kericho', 'Kericho'), ('Samburu', 'Samburu'), ('Kisii', 'Kisii'), ('Marsabit', 'Marsabit'), ('Migori', 'Migori'), ('Mandera', 'Mandera'), ('Kakamega', 'Kakamega'), ('Siaya', 'Siaya'), ('Homa Bay', 'Homa Bay'), ('Embu', 'Embu'), ('Taita-Taveta', 'Taita-Taveta'), ('Kwale', 'Kwale'), ('Makueni', 'Makueni'), ('Machakos', 'Machakos'), ('Mombasa', 'Mombasa')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default=uuid.UUID('022d1c97-e58c-4f4a-b5de-866fd3a822ec'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
