# Generated by Django 3.0.5 on 2023-07-15 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0018_auto_20230715_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Kirinyaga', 'Kirinyaga'), ('Wajir', 'Wajir'), ('Kakamega', 'Kakamega'), ('Kisii', 'Kisii'), ('Nyamira', 'Nyamira'), ('Tana River', 'Tana River'), ('Kisumu', 'Kisumu'), ('Homa Bay', 'Homa Bay'), ('Taita-Taveta', 'Taita-Taveta'), ('Siaya', 'Siaya'), ('Marsabit', 'Marsabit'), ('Busia', 'Busia'), ("Murang'a", 'Murang'), ('Nyeri', 'Nyeri'), ('Vihiga', 'Vihiga'), ('Nairobi', 'Nairobi'), ('Mandera', 'Mandera'), ('Migori', 'Migori'), ('Nandi', 'Nandi'), ('Makueni', 'Makueni'), ('Kilifi', 'Kilifi'), ('Kiambu', 'Kiambu'), ('Lamu', 'Lamu'), ('Machakos', 'Machakos'), ('Bomet', 'Bomet'), ('Uasin Gishu', 'Uasin Gishu'), ('Kajiado', 'Kajiado'), ('Bungoma', 'Bungoma'), ('Mombasa', 'Mombasa'), ('Trans Nzoia', 'Trans Nzoia'), ('Kwale', 'Kwale'), ('Kericho', 'Kericho'), ('Garissa', 'Garissa'), ('Turkana', 'Turkana'), ('Kitui', 'Kitui'), ('Nyandarua', 'Nyandarua'), ('Baringo', 'Baringo'), ('Samburu', 'Samburu'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Meru', 'Meru'), ('Narok', 'Narok'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('West Pokot', 'West Pokot'), ('Isiolo', 'Homa Bay'), ('Laikipia', 'Laikipia'), ('Nakuru', 'Nakuru'), ('Embu', 'Embu')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default=uuid.UUID('39b687f5-0043-4186-882f-ab012f53bdc7'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
