# Generated by Django 3.0.5 on 2023-07-16 07:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0023_auto_20230716_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Mandera', 'Mandera'), ('Laikipia', 'Laikipia'), ('Siaya', 'Siaya'), ('Narok', 'Narok'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Migori', 'Migori'), ('Uasin Gishu', 'Uasin Gishu'), ('Homa Bay', 'Homa Bay'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Mombasa', 'Mombasa'), ('Kirinyaga', 'Kirinyaga'), ('Baringo', 'Baringo'), ('Trans Nzoia', 'Trans Nzoia'), ('Nairobi', 'Nairobi'), ('Wajir', 'Wajir'), ("Murang'a", 'Murang'), ('Marsabit', 'Marsabit'), ('Kisii', 'Kisii'), ('Nandi', 'Nandi'), ('Machakos', 'Machakos'), ('Busia', 'Busia'), ('Garissa', 'Garissa'), ('West Pokot', 'West Pokot'), ('Samburu', 'Samburu'), ('Embu', 'Embu'), ('Nyandarua', 'Nyandarua'), ('Isiolo', 'Homa Bay'), ('Taita-Taveta', 'Taita-Taveta'), ('Bomet', 'Bomet'), ('Vihiga', 'Vihiga'), ('Turkana', 'Turkana'), ('Kisumu', 'Kisumu'), ('Kilifi', 'Kilifi'), ('Nyeri', 'Nyeri'), ('Makueni', 'Makueni'), ('Nyamira', 'Nyamira'), ('Kericho', 'Kericho'), ('Lamu', 'Lamu'), ('Kakamega', 'Kakamega'), ('Kajiado', 'Kajiado'), ('Nakuru', 'Nakuru'), ('Tana River', 'Tana River'), ('Kitui', 'Kitui'), ('Bungoma', 'Bungoma'), ('Meru', 'Meru'), ('Kiambu', 'Kiambu'), ('Kwale', 'Kwale')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default=uuid.UUID('62065e20-24a0-4720-aed9-8d85b77d7d3e'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
