# Generated by Django 4.2.3 on 2023-07-17 06:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0024_auto_20230716_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Siaya', 'Siaya'), ('Vihiga', 'Vihiga'), ('Trans Nzoia', 'Trans Nzoia'), ('Kwale', 'Kwale'), ('Makueni', 'Makueni'), ('West Pokot', 'West Pokot'), ('Homa Bay', 'Homa Bay'), ('Kisii', 'Kisii'), ('Nyandarua', 'Nyandarua'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kitui', 'Kitui'), ("Murang'a", 'Murang'), ('Kiambu', 'Kiambu'), ('Embu', 'Embu'), ('Wajir', 'Wajir'), ('Busia', 'Busia'), ('Garissa', 'Garissa'), ('Mombasa', 'Mombasa'), ('Migori', 'Migori'), ('Mandera', 'Mandera'), ('Kajiado', 'Kajiado'), ('Nandi', 'Nandi'), ('Kirinyaga', 'Kirinyaga'), ('Nakuru', 'Nakuru'), ('Bomet', 'Bomet'), ('Bungoma', 'Bungoma'), ('Machakos', 'Machakos'), ('Nairobi', 'Nairobi'), ('Kericho', 'Kericho'), ('Turkana', 'Turkana'), ('Uasin Gishu', 'Uasin Gishu'), ('Tana River', 'Tana River'), ('Taita-Taveta', 'Taita-Taveta'), ('Lamu', 'Lamu'), ('Marsabit', 'Marsabit'), ('Kilifi', 'Kilifi'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Laikipia', 'Laikipia'), ('Isiolo', 'Homa Bay'), ('Meru', 'Meru'), ('Nyamira', 'Nyamira'), ('Baringo', 'Baringo'), ('Nyeri', 'Nyeri'), ('Samburu', 'Samburu'), ('Kisumu', 'Kisumu'), ('Kakamega', 'Kakamega'), ('Narok', 'Narok')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default=uuid.UUID('9cc9817e-18f3-4e0e-bcca-b7aefb8a124d'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
