# Generated by Django 4.2.3 on 2023-07-17 08:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0025_alter_blooddrives_county_alter_blooddrives_drive_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Mombasa', 'Mombasa'), ('Kirinyaga', 'Kirinyaga'), ('Bomet', 'Bomet'), ('Kisii', 'Kisii'), ('Lamu', 'Lamu'), ('Nairobi', 'Nairobi'), ('Wajir', 'Wajir'), ('West Pokot', 'West Pokot'), ('Laikipia', 'Laikipia'), ('Meru', 'Meru'), ('Homa Bay', 'Homa Bay'), ('Kakamega', 'Kakamega'), ('Kitui', 'Kitui'), ('Garissa', 'Garissa'), ('Narok', 'Narok'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Busia', 'Busia'), ('Kisumu', 'Kisumu'), ('Machakos', 'Machakos'), ('Samburu', 'Samburu'), ('Nandi', 'Nandi'), ('Kiambu', 'Kiambu'), ('Tana River', 'Tana River'), ("Murang'a", 'Murang'), ('Vihiga', 'Vihiga'), ('Bungoma', 'Bungoma'), ('Uasin Gishu', 'Uasin Gishu'), ('Kwale', 'Kwale'), ('Taita-Taveta', 'Taita-Taveta'), ('Nyandarua', 'Nyandarua'), ('Kericho', 'Kericho'), ('Marsabit', 'Marsabit'), ('Nakuru', 'Nakuru'), ('Baringo', 'Baringo'), ('Siaya', 'Siaya'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kajiado', 'Kajiado'), ('Migori', 'Migori'), ('Kilifi', 'Kilifi'), ('Nyeri', 'Nyeri'), ('Trans Nzoia', 'Trans Nzoia'), ('Nyamira', 'Nyamira'), ('Isiolo', 'Homa Bay'), ('Embu', 'Embu'), ('Mandera', 'Mandera'), ('Makueni', 'Makueni'), ('Turkana', 'Turkana')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default=uuid.UUID('e6c9b1cb-9aad-4d6d-8c46-a736ec6cbbaf'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
