# Generated by Django 4.2.3 on 2023-07-17 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0027_alter_blooddrives_county_alter_blooddrives_drive_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Nyeri', 'Nyeri'), ('Kericho', 'Kericho'), ('Bungoma', 'Bungoma'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Nandi', 'Nandi'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ("Murang'a", 'Murang'), ('Bomet', 'Bomet'), ('Nyamira', 'Nyamira'), ('Isiolo', 'Homa Bay'), ('Mombasa', 'Mombasa'), ('Kitui', 'Kitui'), ('Kiambu', 'Kiambu'), ('Kwale', 'Kwale'), ('Trans Nzoia', 'Trans Nzoia'), ('Lamu', 'Lamu'), ('Nakuru', 'Nakuru'), ('Tana River', 'Tana River'), ('Garissa', 'Garissa'), ('Kisumu', 'Kisumu'), ('Vihiga', 'Vihiga'), ('Migori', 'Migori'), ('Makueni', 'Makueni'), ('Nairobi', 'Nairobi'), ('Machakos', 'Machakos'), ('Embu', 'Embu'), ('Meru', 'Meru'), ('West Pokot', 'West Pokot'), ('Busia', 'Busia'), ('Narok', 'Narok'), ('Uasin Gishu', 'Uasin Gishu'), ('Wajir', 'Wajir'), ('Laikipia', 'Laikipia'), ('Siaya', 'Siaya'), ('Taita-Taveta', 'Taita-Taveta'), ('Kirinyaga', 'Kirinyaga'), ('Marsabit', 'Marsabit'), ('Kilifi', 'Kilifi'), ('Mandera', 'Mandera'), ('Kajiado', 'Kajiado'), ('Baringo', 'Baringo'), ('Samburu', 'Samburu'), ('Kisii', 'Kisii'), ('Homa Bay', 'Homa Bay'), ('Turkana', 'Turkana'), ('Nyandarua', 'Nyandarua'), ('Kakamega', 'Kakamega')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default=uuid.UUID('314bcb31-6145-4484-8968-553d9f01e4f9'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
