# Generated by Django 4.2.3 on 2023-07-17 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0028_alter_blooddrives_county_alter_blooddrives_drive_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Baringo', 'Baringo'), ('Meru', 'Meru'), ('Busia', 'Busia'), ('Laikipia', 'Laikipia'), ('Mombasa', 'Mombasa'), ('Mandera', 'Mandera'), ('Kisumu', 'Kisumu'), ('Makueni', 'Makueni'), ('Vihiga', 'Vihiga'), ('Marsabit', 'Marsabit'), ('Turkana', 'Turkana'), ('Isiolo', 'Homa Bay'), ('Kisii', 'Kisii'), ('Taita-Taveta', 'Taita-Taveta'), ('Kilifi', 'Kilifi'), ('Garissa', 'Garissa'), ('Bungoma', 'Bungoma'), ('Kericho', 'Kericho'), ('Bomet', 'Bomet'), ('Nyeri', 'Nyeri'), ('Samburu', 'Samburu'), ('Wajir', 'Wajir'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Uasin Gishu', 'Uasin Gishu'), ('Kirinyaga', 'Kirinyaga'), ('Kwale', 'Kwale'), ('Siaya', 'Siaya'), ('Kitui', 'Kitui'), ("Murang'a", 'Murang'), ('Trans Nzoia', 'Trans Nzoia'), ('Nyamira', 'Nyamira'), ('Machakos', 'Machakos'), ('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Lamu', 'Lamu'), ('Kajiado', 'Kajiado'), ('Kiambu', 'Kiambu'), ('Migori', 'Migori'), ('Narok', 'Narok'), ('Homa Bay', 'Homa Bay'), ('Tana River', 'Tana River'), ('Embu', 'Embu'), ('Nyandarua', 'Nyandarua'), ('Kakamega', 'Kakamega'), ('Nandi', 'Nandi'), ('West Pokot', 'West Pokot'), ('Tharaka-Nithi', 'Tharaka-Nithi')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default=uuid.UUID('054935c1-2361-456f-ba1d-717e32d42c48'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
