# Generated by Django 4.2.3 on 2023-07-17 16:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0029_alter_blooddrives_county_alter_blooddrives_drive_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Kiambu', 'Kiambu'), ('Isiolo', 'Homa Bay'), ('Kwale', 'Kwale'), ('Kilifi', 'Kilifi'), ('Bungoma', 'Bungoma'), ('Kitui', 'Kitui'), ("Murang'a", 'Murang'), ('Uasin Gishu', 'Uasin Gishu'), ('Machakos', 'Machakos'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Bomet', 'Bomet'), ('Samburu', 'Samburu'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kisumu', 'Kisumu'), ('Migori', 'Migori'), ('Narok', 'Narok'), ('Kisii', 'Kisii'), ('Embu', 'Embu'), ('Laikipia', 'Laikipia'), ('Garissa', 'Garissa'), ('Mombasa', 'Mombasa'), ('Nairobi', 'Nairobi'), ('Vihiga', 'Vihiga'), ('Marsabit', 'Marsabit'), ('Lamu', 'Lamu'), ('Mandera', 'Mandera'), ('Busia', 'Busia'), ('Meru', 'Meru'), ('Kericho', 'Kericho'), ('West Pokot', 'West Pokot'), ('Nakuru', 'Nakuru'), ('Turkana', 'Turkana'), ('Kakamega', 'Kakamega'), ('Taita-Taveta', 'Taita-Taveta'), ('Nandi', 'Nandi'), ('Nyamira', 'Nyamira'), ('Wajir', 'Wajir'), ('Tana River', 'Tana River'), ('Nyandarua', 'Nyandarua'), ('Baringo', 'Baringo'), ('Makueni', 'Makueni'), ('Kajiado', 'Kajiado'), ('Homa Bay', 'Homa Bay'), ('Kirinyaga', 'Kirinyaga'), ('Nyeri', 'Nyeri'), ('Trans Nzoia', 'Trans Nzoia'), ('Siaya', 'Siaya')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default=uuid.UUID('f140bb23-79ef-4335-9dba-2dc0b13cc887'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
