# Generated by Django 4.2.3 on 2023-07-17 17:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0030_alter_blooddrives_county_alter_blooddrives_drive_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Taita-Taveta', 'Taita-Taveta'), ('Busia', 'Busia'), ('Mombasa', 'Mombasa'), ('Kiambu', 'Kiambu'), ('Meru', 'Meru'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('West Pokot', 'West Pokot'), ('Lamu', 'Lamu'), ('Kajiado', 'Kajiado'), ('Samburu', 'Samburu'), ('Nandi', 'Nandi'), ("Murang'a", 'Murang'), ('Tana River', 'Tana River'), ('Wajir', 'Wajir'), ('Garissa', 'Garissa'), ('Vihiga', 'Vihiga'), ('Migori', 'Migori'), ('Kisumu', 'Kisumu'), ('Turkana', 'Turkana'), ('Nyamira', 'Nyamira'), ('Siaya', 'Siaya'), ('Machakos', 'Machakos'), ('Kitui', 'Kitui'), ('Nyeri', 'Nyeri'), ('Trans Nzoia', 'Trans Nzoia'), ('Mandera', 'Mandera'), ('Isiolo', 'Homa Bay'), ('Makueni', 'Makueni'), ('Kwale', 'Kwale'), ('Uasin Gishu', 'Uasin Gishu'), ('Kericho', 'Kericho'), ('Embu', 'Embu'), ('Bungoma', 'Bungoma'), ('Bomet', 'Bomet'), ('Narok', 'Narok'), ('Kirinyaga', 'Kirinyaga'), ('Nyandarua', 'Nyandarua'), ('Nakuru', 'Nakuru'), ('Laikipia', 'Laikipia'), ('Kakamega', 'Kakamega'), ('Homa Bay', 'Homa Bay'), ('Kisii', 'Kisii'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Kilifi', 'Kilifi'), ('Nairobi', 'Nairobi'), ('Baringo', 'Baringo'), ('Marsabit', 'Marsabit')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default=uuid.UUID('bfacdf40-b040-498d-80ab-905016aabf11'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
