# Generated by Django 4.2.3 on 2023-07-17 17:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0032_alter_blooddrives_county_alter_blooddrives_drive_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Vihiga', 'Vihiga'), ('Bomet', 'Bomet'), ('Kiambu', 'Kiambu'), ('Siaya', 'Siaya'), ('Meru', 'Meru'), ('Trans Nzoia', 'Trans Nzoia'), ('Migori', 'Migori'), ('Samburu', 'Samburu'), ('Nairobi', 'Nairobi'), ('Nyeri', 'Nyeri'), ('Taita-Taveta', 'Taita-Taveta'), ('Makueni', 'Makueni'), ('Nyamira', 'Nyamira'), ('Embu', 'Embu'), ('Mombasa', 'Mombasa'), ('Machakos', 'Machakos'), ('Kwale', 'Kwale'), ('Tana River', 'Tana River'), ('Nandi', 'Nandi'), ('Nakuru', 'Nakuru'), ('Lamu', 'Lamu'), ('Kakamega', 'Kakamega'), ("Murang'a", 'Murang'), ('Turkana', 'Turkana'), ('Busia', 'Busia'), ('Kajiado', 'Kajiado'), ('Wajir', 'Wajir'), ('West Pokot', 'West Pokot'), ('Kitui', 'Kitui'), ('Kisumu', 'Kisumu'), ('Homa Bay', 'Homa Bay'), ('Nyandarua', 'Nyandarua'), ('Kilifi', 'Kilifi'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Garissa', 'Garissa'), ('Uasin Gishu', 'Uasin Gishu'), ('Kirinyaga', 'Kirinyaga'), ('Bungoma', 'Bungoma'), ('Baringo', 'Baringo'), ('Laikipia', 'Laikipia'), ('Marsabit', 'Marsabit'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Mandera', 'Mandera'), ('Narok', 'Narok'), ('Kericho', 'Kericho'), ('Isiolo', 'Homa Bay'), ('Kisii', 'Kisii')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default=uuid.UUID('3d583536-d5cd-4128-92dc-5bc278f212c7'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
