# Generated by Django 4.2.3 on 2023-07-17 20:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0034_alter_blooddrives_county_alter_blooddrives_drive_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Narok', 'Narok'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Garissa', 'Garissa'), ('Homa Bay', 'Homa Bay'), ('Lamu', 'Lamu'), ('Bomet', 'Bomet'), ('Taita-Taveta', 'Taita-Taveta'), ('Kwale', 'Kwale'), ('Kericho', 'Kericho'), ('Nakuru', 'Nakuru'), ('Trans Nzoia', 'Trans Nzoia'), ('Bungoma', 'Bungoma'), ('Nyeri', 'Nyeri'), ('Kisii', 'Kisii'), ('Machakos', 'Machakos'), ('Siaya', 'Siaya'), ('Busia', 'Busia'), ('Kisumu', 'Kisumu'), ('Uasin Gishu', 'Uasin Gishu'), ('Baringo', 'Baringo'), ('Kilifi', 'Kilifi'), ("Murang'a", 'Murang'), ('West Pokot', 'West Pokot'), ('Makueni', 'Makueni'), ('Wajir', 'Wajir'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Migori', 'Migori'), ('Kitui', 'Kitui'), ('Turkana', 'Turkana'), ('Vihiga', 'Vihiga'), ('Laikipia', 'Laikipia'), ('Mandera', 'Mandera'), ('Meru', 'Meru'), ('Nyandarua', 'Nyandarua'), ('Nyamira', 'Nyamira'), ('Marsabit', 'Marsabit'), ('Embu', 'Embu'), ('Kiambu', 'Kiambu'), ('Kakamega', 'Kakamega'), ('Samburu', 'Samburu'), ('Isiolo', 'Homa Bay'), ('Mombasa', 'Mombasa'), ('Kirinyaga', 'Kirinyaga'), ('Tana River', 'Tana River'), ('Kajiado', 'Kajiado'), ('Nandi', 'Nandi')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default=uuid.UUID('24cfaf6d-6c6b-42f1-867d-322ab6018ed8'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
