# Generated by Django 4.2.3 on 2023-07-20 09:01

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0036_alter_blooddrives_county_alter_blooddrives_drive_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='bloodgroup',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='request_by_patient',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('B+', 'B+'), ('O-', 'O-'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('A', 'A'), ('A+', 'A+'), ('B-', 'B-'), ('O+', 'O+')], default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='assistance/docs/'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='email',
            field=models.EmailField(default='request@placeholder.com', max_length=254),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='id_b_photo',
            field=models.ImageField(null=True, upload_to='assistance/id_back'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='id_f_photo',
            field=models.ImageField(null=True, upload_to='assistance/id_front'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='referral_mobile',
            field=models.CharField(default="doctor's mobile", max_length=16),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='referred_person',
            field=models.CharField(default='eg. your doctor', max_length=30),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Kisii', 'Kisii'), ('Wajir', 'Wajir'), ('Bungoma', 'Bungoma'), ('Bomet', 'Bomet'), ('Makueni', 'Makueni'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Busia', 'Busia'), ('Embu', 'Embu'), ('Machakos', 'Machakos'), ('Lamu', 'Lamu'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Taita-Taveta', 'Taita-Taveta'), ('Mandera', 'Mandera'), ('Laikipia', 'Laikipia'), ('Migori', 'Migori'), ('Nandi', 'Nandi'), ('Kisumu', 'Kisumu'), ('Nairobi', 'Nairobi'), ('Nyamira', 'Nyamira'), ('Turkana', 'Turkana'), ('Nyeri', 'Nyeri'), ('Uasin Gishu', 'Uasin Gishu'), ("Murang'a", 'Murang'), ('Kericho', 'Kericho'), ('Kilifi', 'Kilifi'), ('Trans Nzoia', 'Trans Nzoia'), ('Kakamega', 'Kakamega'), ('Garissa', 'Garissa'), ('Tana River', 'Tana River'), ('Meru', 'Meru'), ('Nakuru', 'Nakuru'), ('Kiambu', 'Kiambu'), ('Kitui', 'Kitui'), ('Isiolo', 'Homa Bay'), ('Mombasa', 'Mombasa'), ('Samburu', 'Samburu'), ('West Pokot', 'West Pokot'), ('Kirinyaga', 'Kirinyaga'), ('Kwale', 'Kwale'), ('Nyandarua', 'Nyandarua'), ('Homa Bay', 'Homa Bay'), ('Narok', 'Narok'), ('Baringo', 'Baringo'), ('Vihiga', 'Vihiga'), ('Kajiado', 'Kajiado'), ('Siaya', 'Siaya'), ('Marsabit', 'Marsabit')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default=uuid.UUID('9922b14a-6426-4caf-8261-d65d6fa377fd'), max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 20, 12, 1, 19, 329462)),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20),
        ),
    ]
