# Generated by Django 4.2.3 on 2023-07-23 15:28

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0037_remove_bloodrequest_bloodgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Meru', 'Meru'), ('Mombasa', 'Mombasa'), ('Tana River', 'Tana River'), ('Lamu', 'Lamu'), ('Marsabit', 'Marsabit'), ('Uasin Gishu', 'Uasin Gishu'), ('Embu', 'Embu'), ('Siaya', 'Siaya'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Kitui', 'Kitui'), ('Kajiado', 'Kajiado'), ('Bomet', 'Bomet'), ('West Pokot', 'West Pokot'), ('Isiolo', 'Homa Bay'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kwale', 'Kwale'), ('Kisumu', 'Kisumu'), ('Nyeri', 'Nyeri'), ('Garissa', 'Garissa'), ('Machakos', 'Machakos'), ('Migori', 'Migori'), ('Baringo', 'Baringo'), ('Kisii', 'Kisii'), ('Nairobi', 'Nairobi'), ('Turkana', 'Turkana'), ('Nyamira', 'Nyamira'), ('Trans Nzoia', 'Trans Nzoia'), ('Kericho', 'Kericho'), ('Nyandarua', 'Nyandarua'), ('Homa Bay', 'Homa Bay'), ('Busia', 'Busia'), ('Nakuru', 'Nakuru'), ('Kirinyaga', 'Kirinyaga'), ("Murang'a", "Murang'a"), ('Wajir', 'Wajir'), ('Nandi', 'Nandi'), ('Mandera', 'Mandera'), ('Laikipia', 'Laikipia'), ('Kakamega', 'Kakamega'), ('Narok', 'Narok'), ('Vihiga', 'Vihiga'), ('Kilifi', 'Kilifi'), ('Makueni', 'Makueni'), ('Bungoma', 'Bungoma'), ('Samburu', 'Samburu'), ('Kiambu', 'Kiambu'), ('Taita-Taveta', 'Taita-Taveta')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default=uuid.UUID('1812ede5-6ecc-4af7-97a1-6e5b8c8a596e'), max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O-', 'O-'), ('AB-', 'AB-'), ('B-', 'B-'), ('A', 'A'), ('O+', 'O+')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 23, 18, 28, 20, 461556)),
        ),
    ]
