# Generated by Django 4.2.3 on 2023-07-24 04:25

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0038_alter_blooddrives_county_alter_blooddrives_drive_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Uasin Gishu', 'Uasin Gishu'), ('Kisumu', 'Kisumu'), ('Samburu', 'Samburu'), ('Bomet', 'Bomet'), ('Taita-Taveta', 'Taita-Taveta'), ('Kakamega', 'Kakamega'), ('Embu', 'Embu'), ('Marsabit', 'Marsabit'), ('Kisii', 'Kisii'), ('Turkana', 'Turkana'), ('Makueni', 'Makueni'), ('Isiolo', 'Homa Bay'), ('Machakos', 'Machakos'), ('Laikipia', 'Laikipia'), ('Migori', 'Migori'), ('Busia', 'Busia'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Siaya', 'Siaya'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Narok', 'Narok'), ('Garissa', 'Garissa'), ('Nandi', 'Nandi'), ('Nakuru', 'Nakuru'), ('Wajir', 'Wajir'), ('Kitui', 'Kitui'), ('Kwale', 'Kwale'), ('Bungoma', 'Bungoma'), ('Vihiga', 'Vihiga'), ('Kiambu', 'Kiambu'), ('Kajiado', 'Kajiado'), ('Baringo', 'Baringo'), ('Nyandarua', 'Nyandarua'), ('Homa Bay', 'Homa Bay'), ('Kirinyaga', 'Kirinyaga'), ('Nyamira', 'Nyamira'), ('Nyeri', 'Nyeri'), ('Trans Nzoia', 'Trans Nzoia'), ('West Pokot', 'West Pokot'), ("Murang'a", "Murang'a"), ('Mandera', 'Mandera'), ('Kilifi', 'Kilifi'), ('Kericho', 'Kericho'), ('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Tana River', 'Tana River'), ('Meru', 'Meru'), ('Lamu', 'Lamu')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default=uuid.UUID('6274f841-34e8-4319-b8d3-a455ca1582db'), max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('B-', 'B-'), ('AB+', 'AB+'), ('A', 'A'), ('O-', 'O-'), ('B+', 'B+'), ('O+', 'O+'), ('AB-', 'AB-')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 24, 7, 25, 3, 902439)),
        ),
    ]
