# Generated by Django 4.2.3 on 2023-07-24 11:05

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0041_alter_blooddrives_county_alter_blooddrives_drive_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Nakuru', 'Nakuru'), ('Kwale', 'Kwale'), ('Nyamira', 'Nyamira'), ('Nyandarua', 'Nyandarua'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Narok', 'Narok'), ('Baringo', 'Baringo'), ('Mombasa', 'Mombasa'), ('Siaya', 'Siaya'), ('Kiambu', 'Kiambu'), ('Meru', 'Meru'), ('Bomet', 'Bomet'), ('Bungoma', 'Bungoma'), ('Embu', 'Embu'), ('Taita-Taveta', 'Taita-Taveta'), ('Nyeri', 'Nyeri'), ('Makueni', 'Makueni'), ('West Pokot', 'West Pokot'), ('Isiolo', 'Homa Bay'), ('Kitui', 'Kitui'), ('Turkana', 'Turkana'), ('Machakos', 'Machakos'), ('Kisii', 'Kisii'), ('Kakamega', 'Kakamega'), ('Kilifi', 'Kilifi'), ('Wajir', 'Wajir'), ('Laikipia', 'Laikipia'), ('Homa Bay', 'Homa Bay'), ('Uasin Gishu', 'Uasin Gishu'), ('Vihiga', 'Vihiga'), ('Busia', 'Busia'), ('Migori', 'Migori'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Samburu', 'Samburu'), ('Lamu', 'Lamu'), ("Murang'a", "Murang'a"), ('Garissa', 'Garissa'), ('Mandera', 'Mandera'), ('Kericho', 'Kericho'), ('Trans Nzoia', 'Trans Nzoia'), ('Kirinyaga', 'Kirinyaga'), ('Marsabit', 'Marsabit'), ('Tana River', 'Tana River'), ('Nandi', 'Nandi'), ('Kajiado', 'Kajiado'), ('Nairobi', 'Nairobi'), ('Kisumu', 'Kisumu')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default=uuid.UUID('c756e9a1-a14e-451c-89d8-0dc18a0d72e6'), max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('A+', 'A+'), ('B-', 'B-'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 24, 14, 5, 18, 258059)),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
