# Generated by Django 4.2.3 on 2023-08-19 18:56

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0043_alter_blooddrives_county_alter_blooddrives_drive_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Bungoma', 'Bungoma'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kitui', 'Kitui'), ('Kiambu', 'Kiambu'), ('Laikipia', 'Laikipia'), ('Kericho', 'Kericho'), ('Kajiado', 'Kajiado'), ('Marsabit', 'Marsabit'), ('Mandera', 'Mandera'), ('Embu', 'Embu'), ('Nyamira', 'Nyamira'), ('Nyeri', 'Nyeri'), ('Trans Nzoia', 'Trans Nzoia'), ('Meru', 'Meru'), ('Kisii', 'Kisii'), ("Murang'a", "Murang'a"), ('Samburu', 'Samburu'), ('Nandi', 'Nandi'), ('Kwale', 'Kwale'), ('Garissa', 'Garissa'), ('Migori', 'Migori'), ('Tana River', 'Tana River'), ('West Pokot', 'West Pokot'), ('Lamu', 'Lamu'), ('Busia', 'Busia'), ('Siaya', 'Siaya'), ('Kirinyaga', 'Kirinyaga'), ('Uasin Gishu', 'Uasin Gishu'), ('Nyandarua', 'Nyandarua'), ('Kakamega', 'Kakamega'), ('Kilifi', 'Kilifi'), ('Machakos', 'Machakos'), ('Isiolo', 'Homa Bay'), ('Wajir', 'Wajir'), ('Taita-Taveta', 'Taita-Taveta'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Homa Bay', 'Homa Bay'), ('Vihiga', 'Vihiga'), ('Makueni', 'Makueni'), ('Baringo', 'Baringo'), ('Nairobi', 'Nairobi'), ('Narok', 'Narok'), ('Bomet', 'Bomet'), ('Nakuru', 'Nakuru'), ('Turkana', 'Turkana')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default=uuid.UUID('7bff2a56-daf8-4519-8a09-e61184b53b88'), max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('B-', 'B-'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('A', 'A'), ('O-', 'O-'), ('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 19, 21, 56, 30, 222578)),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
