# Generated by Django 4.2.3 on 2023-08-22 18:32

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0044_alter_blooddrives_county_alter_blooddrives_drive_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Homa Bay', 'Homa Bay'), ("Murang'a", "Murang'a"), ('Wajir', 'Wajir'), ('Nyandarua', 'Nyandarua'), ('Turkana', 'Turkana'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kilifi', 'Kilifi'), ('Kisii', 'Kisii'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Makueni', 'Makueni'), ('Tana River', 'Tana River'), ('Kirinyaga', 'Kirinyaga'), ('Migori', 'Migori'), ('Nyeri', 'Nyeri'), ('Busia', 'Busia'), ('Nakuru', 'Nakuru'), ('Nairobi', 'Nairobi'), ('Mandera', 'Mandera'), ('Siaya', 'Siaya'), ('Trans Nzoia', 'Trans Nzoia'), ('Marsabit', 'Marsabit'), ('Isiolo', 'Homa Bay'), ('Bomet', 'Bomet'), ('Machakos', 'Machakos'), ('Kisumu', 'Kisumu'), ('Uasin Gishu', 'Uasin Gishu'), ('Vihiga', 'Vihiga'), ('Baringo', 'Baringo'), ('Meru', 'Meru'), ('Samburu', 'Samburu'), ('Nyamira', 'Nyamira'), ('Kiambu', 'Kiambu'), ('Nandi', 'Nandi'), ('West Pokot', 'West Pokot'), ('Taita-Taveta', 'Taita-Taveta'), ('Kericho', 'Kericho'), ('Narok', 'Narok'), ('Garissa', 'Garissa'), ('Kajiado', 'Kajiado'), ('Kakamega', 'Kakamega'), ('Lamu', 'Lamu'), ('Kitui', 'Kitui'), ('Kwale', 'Kwale'), ('Laikipia', 'Laikipia'), ('Embu', 'Embu'), ('Mombasa', 'Mombasa'), ('Bungoma', 'Bungoma')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default=uuid.UUID('8be0ddc0-631c-4fd1-abcf-205e49f6b842'), max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('B-', 'B-'), ('A+', 'A+'), ('B+', 'B+'), ('AB-', 'AB-'), ('A', 'A'), ('AB+', 'AB+')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 22, 21, 32, 51, 758714)),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
