# Generated by Django 4.2.3 on 2023-08-23 08:45

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0045_alter_blooddrives_county_alter_blooddrives_drive_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddrives',
            name='county',
            field=models.CharField(choices=[('Nakuru', 'Nakuru'), ('Kwale', 'Kwale'), ('Kakamega', 'Kakamega'), ('Lamu', 'Lamu'), ('Baringo', 'Baringo'), ('Nairobi', 'Nairobi'), ('Laikipia', 'Laikipia'), ('Garissa', 'Garissa'), ('Tana River', 'Tana River'), ('Meru', 'Meru'), ('Embu', 'Embu'), ('Narok', 'Narok'), ('Nyamira', 'Nyamira'), ('Kisumu', 'Kisumu'), ("Murang'a", "Murang'a"), ('Bomet', 'Bomet'), ('Mandera', 'Mandera'), ('Taita-Taveta', 'Taita-Taveta'), ('Nyandarua', 'Nyandarua'), ('Nandi', 'Nandi'), ('Busia', 'Busia'), ('Machakos', 'Machakos'), ('Bungoma', 'Bungoma'), ('Isiolo', 'Homa Bay'), ('Vihiga', 'Vihiga'), ('Homa Bay', 'Homa Bay'), ('Kericho', 'Kericho'), ('Samburu', 'Samburu'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Kirinyaga', 'Kirinyaga'), ('Marsabit', 'Marsabit'), ('Siaya', 'Siaya'), ('Kisii', 'Kisii'), ('Uasin Gishu', 'Uasin Gishu'), ('West Pokot', 'West Pokot'), ('Kiambu', 'Kiambu'), ('Mombasa', 'Mombasa'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Wajir', 'Wajir'), ('Kitui', 'Kitui'), ('Nyeri', 'Nyeri'), ('Turkana', 'Turkana'), ('Trans Nzoia', 'Trans Nzoia'), ('Kajiado', 'Kajiado'), ('Kilifi', 'Kilifi'), ('Migori', 'Migori'), ('Makueni', 'Makueni')], max_length=15),
        ),
        migrations.AlterField(
            model_name='blooddrives',
            name='drive_id',
            field=models.CharField(default=uuid.UUID('0cf8f2cd-4f26-450b-bd62-5926689cb756'), max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('B+', 'B+'), ('O-', 'O-'), ('B-', 'B-'), ('A+', 'A+'), ('A', 'A'), ('AB+', 'AB+'), ('O+', 'O+'), ('AB-', 'AB-')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 23, 11, 45, 20, 747232)),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
